import { useEffect, useState } from 'react'
import { useParams, useSearchParams } from 'react-router-dom'
import { getLecturerCourseClass, listLecturerCourseClasses } from '../../api/academicsApi'
import ClassWorkspace from '../../components/common/ClassWorkspace'
import CourseCard from '../../components/common/CourseCard'
import CourseFilters from '../../components/common/CourseFilters'
import PageHeader from '../../components/common/PageHeader'
import { EmptyState, ErrorState, LoadingState } from '../../components/common/UiState'

const initial = { search: '', academicYearId: '', semesterId: '', subjectId: '', status: '', academicYears: [], semesters: [], subjects: [] }
const unique = (items, id, name, code, key = id) => [...new Map(items.filter(item => item[id]).map(item => [String(item[key] || item[id]).trim().toLocaleLowerCase('vi'), { id: item[id], name: item[name], code: item[code] }])).values()]
const paramsOf = ({ search, academicYearId, semesterId, subjectId, status }) => ({ search, academicYearId, semesterId, subjectId, status })

export default function LecturerCourseClassesPage() {
  const { id } = useParams(); const [searchParams] = useSearchParams(); const activeTab = searchParams.get('tab') || ''; const [items, setItems] = useState([]); const [detail, setDetail] = useState(null); const [filters, setFilters] = useState(initial); const [loading, setLoading] = useState(true); const [error, setError] = useState(null)
  const load = async params => { try { setLoading(true); setError(null); setDetail(null); if (id) { const response=await getLecturerCourseClass(id); if(!response?.data) setError({status:404,message:'Không tìm thấy lớp học phần.'}); else setDetail(response.data) } else { const response = await listLecturerCourseClasses({ ...paramsOf(params), pageSize: 100 }); const rows = response.data.items || []; setItems(rows); setFilters(current => ({ ...current, academicYears: current.academicYears.length ? current.academicYears : unique(rows, 'academicYearId', 'academicYearName'), semesters: current.semesters.length ? current.semesters : unique(rows, 'semesterId', 'semesterName', undefined, 'semesterName'), subjects: current.subjects.length ? current.subjects : unique(rows, 'subjectId', 'subjectName', 'subjectCode') })) } } catch (err) { setError({status:err.status,message:err.status===403?'Bạn không có quyền truy cập lớp học phần này.':err.status===404?'Không tìm thấy lớp học phần.':err.message}) } finally { setLoading(false) } }
  useEffect(() => { load({}) }, [id])
  if (loading) return <div className="panel"><LoadingState label="Đang tải lớp phụ trách..." /></div>
  if (error) return <div className="panel"><ErrorState message={error.message} onRetry={() => load(filters)} /></div>
  if (id && !detail) return <div className="panel"><EmptyState title="Không tìm thấy lớp học phần" description="Lớp không tồn tại hoặc bạn chưa được phân công phụ trách." /></div>
  if (id) return <ClassWorkspace course={detail} role="lecturer" activeTab={activeTab}>{activeTab === 'students' ? <section className="panel workspace-content"><div className="workspace-section-heading"><div><h3>Sinh viên lớp học phần</h3><p>Danh sách sinh viên đang được ghi danh trong lớp <strong>{detail.code}</strong>.</p></div><span className="status-badge-ui blue">{detail.students?.length || 0} sinh viên</span></div>{detail.students?.length ? <div className="table-wrap"><table><thead><tr><th>Mã sinh viên</th><th>Họ và tên</th><th>Email</th></tr></thead><tbody>{detail.students.map(student => <tr key={student.id}><td><strong>{student.studentCode || '—'}</strong></td><td>{student.fullName}</td><td className="breakable-text">{student.email}</td></tr>)}</tbody></table></div> : <EmptyState title="Lớp chưa có sinh viên" description="Danh sách sẽ hiển thị tại đây khi có sinh viên được ghi danh vào lớp học phần." />}</section> : <section className="panel workspace-content"><EmptyState title="Chức năng đang được cập nhật" description="Nội dung của mục này sẽ sớm được bổ sung." /></section>}</ClassWorkspace>
  return <div><PageHeader eyebrow="Không gian giảng viên" title="Lớp học phần phụ trách" description="Mỗi lớp là một không gian dự án độc lập theo đúng mã lớp học phần." /><CourseFilters filters={filters} onChange={setFilters} onSubmit={event => { event.preventDefault(); load(filters) }} />{items.length ? <div className="course-grid">{items.map((course, index) => <CourseCard role="lecturer" key={course.id} course={course} index={index} to={`/lecturer/course-classes/${course.id}`} />)}</div> : <div className="panel"><EmptyState title="Không có lớp phù hợp" description="Không tìm thấy lớp học phần nào trong phạm vi được phân công." /></div>}</div>
}
