import * as repo from './administrativeClasses.repository.js'
const ok=(data,message,statusCode=200)=>({success:true,data,message,statusCode}),fail=(statusCode,message)=>({success:false,statusCode,message}),id=v=>Number.isInteger(Number(v))&&Number(v)>0?Number(v):null
export const list=async()=>ok(await repo.list(),'Lấy danh sách lớp hành chính thành công')
export async function save(value,b){const key=value?id(value):null,d={classCode:String(b.classCode||'').trim().toUpperCase(),className:String(b.className||'').trim(),cohort:String(b.cohort||'').trim(),majorId:id(b.majorId),academicYearId:id(b.academicYearId),status:String(b.status||'ACTIVE').toUpperCase()};if(!d.classCode||!d.className||!['ACTIVE','INACTIVE','GRADUATED'].includes(d.status))return fail(400,'Dữ liệu lớp hành chính không hợp lệ');try{return ok(await repo.save(key,d),key?'Cập nhật lớp thành công':'Tạo lớp thành công',key?200:201)}catch(e){if([2601,2627].includes(e.number))return fail(409,'Mã lớp hành chính đã tồn tại');throw e}}
export async function students(value){const key=id(value);if(!key||!await repo.find(key))return fail(404,'Không tìm thấy lớp hành chính');return ok(await repo.students(key),'Lấy danh sách sinh viên thành công')}
export async function add(value,b,user){const key=id(value),ids=[...new Set((b.studentIds||[]).map(id).filter(Boolean))];if(!key||!await repo.find(key))return fail(404,'Không tìm thấy lớp hành chính');if(!ids.length)return fail(400,'Danh sách sinh viên không hợp lệ');try{return ok(await repo.addStudents(key,ids,user.id),'Thêm sinh viên thành công')}catch(e){if(e.code==='INVALID_STUDENT')return fail(400,'Có sinh viên không hợp lệ hoặc không hoạt động');if(e.code==='CURRENT_CLASS')return fail(409,'Có sinh viên đang thuộc lớp hành chính khác');throw e}}
export async function remove(classId,studentId,b,user){return await repo.removeStudent(id(classId),id(studentId),b.reason,user.id)?ok(null,'Đã xóa sinh viên khỏi lớp hiện tại'):fail(404,'Không tìm thấy membership hiện tại')}
export async function transfer(b,user){if(!id(b.studentId)||!id(b.targetAdministrativeClassId)||!String(b.reason||'').trim())return fail(400,'Sinh viên, lớp đích và lý do là bắt buộc');if(!await repo.find(id(b.targetAdministrativeClassId)))return fail(404,'Không tìm thấy lớp đích');try{return ok(await repo.transfer(id(b.studentId),id(b.targetAdministrativeClassId),String(b.reason).trim(),user.id),'Chuyển lớp thành công')}catch(e){if(['NO_CURRENT','SAME_CLASS'].includes(e.code))return fail(409,e.code==='SAME_CLASS'?'Sinh viên đã ở lớp đích':'Sinh viên chưa có lớp hiện tại');throw e}}
export const history=async studentId=>ok(await repo.history(id(studentId)),'Lấy lịch sử chuyển lớp thành công')
export const mine=async user=>ok({current:await repo.current(user.id),history:await repo.history(user.id)},'Lấy lớp hành chính thành công')
