import { useCallback, useEffect, useMemo, useState } from 'react'
import { Button, List, Progress, Select, Space, Steps } from 'antd'
import { BarChartOutlined, BookOutlined, FolderOutlined, ReloadOutlined, TeamOutlined, UserOutlined } from '@ant-design/icons'
import { Bar, Doughnut, Line } from 'react-chartjs-2'
import { ArcElement, BarElement, CategoryScale, Chart as ChartJS, Legend, LinearScale, LineElement, PointElement, Tooltip } from 'chart.js'
import { getDashboardAnalytics, getDashboardErrorMessage, getRoleDashboard } from '../../api/dashboardApi'
import { AppChartCard, AppErrorState, AppLoadingState, AppPageContainer, AppStatCard, CourseClassCard, DeadlineCard, GroupProgressCard, RecentActivityList } from '../../components/dashboard/DashboardComponents'
import './role-dashboard.css'

ChartJS.register(ArcElement, BarElement, CategoryScale, LinearScale, LineElement, PointElement, Tooltip, Legend)
const colors = ['#164A9C', '#6C5CE7', '#F59E0B', '#EC4899', '#22A06B', '#D92D20']
const statusLabels = { ADMIN: 'Quản trị', LECTURER: 'Giảng viên', STUDENT: 'Sinh viên', PENDING: 'Chờ duyệt', APPROVED: 'Đã duyệt', REJECTED: 'Từ chối', REQUIRES_REVISION: 'Cần chỉnh sửa', SUBMITTED: 'Đã nộp', LATE: 'Nộp trễ', GRADED: 'Đã chấm', UNDER_REVIEW: 'Đang xem xét', RESUBMITTED: 'Nộp lại' }
const chartOptions = (horizontal = false) => ({ responsive: true, maintainAspectRatio: false, animation: false, indexAxis: horizontal ? 'y' : 'x', plugins: { legend: { position: 'bottom' }, tooltip: { callbacks: { label: context => `${context.dataset.label || 'Số lượng'}: ${context.parsed.y ?? context.parsed.x ?? context.parsed}` } } }, scales: horizontal ? { x: { beginAtZero: true, ticks: { precision: 0 } } } : { y: { beginAtZero: true, ticks: { precision: 0 } } } })
const dataset = (items = [], label = 'Số lượng') => ({ labels: items.map(x => statusLabels[x.label] || x.label), datasets: [{ label, data: items.map(x => Number(x.value || 0)), backgroundColor: colors, borderColor: '#164A9C', tension: .25 }] })
const hasData = items => Array.isArray(items) && items.some(item => Number(item.value || 0) > 0)

export default function RoleDashboardPage({ role, title }) {
  const [data, setData] = useState(null), [legacy, setLegacy] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [courseClassId, setCourseClassId] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [analytics, base] = await Promise.all([getDashboardAnalytics(role, courseClassId ? { courseClassId } : {}), getRoleDashboard(role)]); setData(analytics); setLegacy(base.data) } catch (err) { setError(getDashboardErrorMessage(err)) } finally { setLoading(false) } }, [role, courseClassId])
  useEffect(() => { load() }, [load])
  const extra = <Space wrap>{role === 'lecturer' && <Select aria-label="Lọc lớp học phần" allowClear placeholder="Tất cả lớp" style={{ minWidth: 220 }} value={courseClassId || undefined} onChange={value => setCourseClassId(value || '')} options={(legacy?.courseClasses || []).map(c => ({ value: c.id, label: `${c.code} · ${c.subjectName}` }))} />}<Button icon={<ReloadOutlined />} onClick={load}>Làm mới</Button></Space>
  if (loading && !data) return <AppLoadingState />
  if (error && !data) return <AppErrorState message={error} onRetry={load} />
  return <div className="role-dashboard"><AppPageContainer title={title} description="Số liệu được tổng hợp trực tiếp từ hệ thống." extra={extra}>{error && <AppErrorState message={error} onRetry={load} />}{role === 'admin' ? <Admin data={data} /> : role === 'lecturer' ? <Lecturer data={data} legacy={legacy} /> : <Student data={data} legacy={legacy} />}</AppPageContainer></div>
}

function Kpis({ items }) { return <div className="dashboard-kpis">{items.map(([title, value, icon]) => <AppStatCard key={title} title={title} value={value} icon={icon} />)}</div> }
function Admin({ data }) { const s=data.summary||{}; return <><Kpis items={[["Tổng tài khoản",s.totalAccounts,<UserOutlined/>],["Tổng sinh viên",s.totalStudents,<TeamOutlined/>],["Tổng giảng viên",s.totalLecturers,<UserOutlined/>],["Lớp học phần",s.totalCourseClasses,<BookOutlined/>],["Nhóm dự án",s.totalGroups,<TeamOutlined/>],["Đề tài",s.totalTopics,<FolderOutlined/>]]}/><div className="dashboard-charts"><AppChartCard title="Tài khoản theo vai trò" description="Số lượng và tỷ lệ tài khoản theo vai trò" empty={!hasData(data.accountsByRole)}><Doughnut data={dataset(data.accountsByRole)} options={{...chartOptions(),cutout:'62%'}}/></AppChartCard><AppChartCard title="Lớp học phần theo học kỳ" description="Số lớp trong từng học kỳ" empty={!hasData(data.courseClassesBySemester)}><Bar data={dataset(data.courseClassesBySemester)} options={chartOptions()}/></AppChartCard><AppChartCard title="Sinh viên theo khoa" description="Sinh viên thuộc lớp hành chính của từng khoa" empty={!hasData(data.studentsByFaculty)}><Bar data={dataset(data.studentsByFaculty)} options={chartOptions(true)}/></AppChartCard><AppChartCard title="Đề tài theo trạng thái" description="Phân bố trạng thái đề tài thực tế" empty={!hasData(data.topicsByStatus)}><Doughnut data={dataset(data.topicsByStatus)} options={{...chartOptions(),cutout:'62%'}}/></AppChartCard><AppChartCard title="Bài nộp theo tháng" description="Số lượt nộp theo thời gian" empty={!hasData(data.submissionsOverTime)}><Line data={dataset(data.submissionsOverTime,'Lượt nộp')} options={chartOptions()}/></AppChartCard><AppChartCard title="Top môn học theo số lớp" description="Tối đa 10 môn có nhiều lớp học phần" empty={!hasData(data.courseClassesByCourse)}><Bar data={dataset(data.courseClassesByCourse)} options={chartOptions(true)}/></AppChartCard></div><div className="dashboard-secondary"><AppChartCard title="Hoạt động gần đây" description="Tài khoản mới được tạo" empty={!data.recentActivities?.length}><RecentActivityList items={data.recentActivities}/></AppChartCard><AppChartCard title="Dữ liệu cần xử lý" description="Các đề tài đang chờ duyệt" empty={!data.topicsByStatus?.length}><List dataSource={data.topicsByStatus||[]} renderItem={x=><List.Item>{statusLabels[x.label]||x.label}: <strong>{x.value}</strong></List.Item>}/></AppChartCard></div></> }
function Lecturer({ data, legacy }) { const s=data.summary||{}; return <><Kpis items={[["Lớp phụ trách",s.classes,<BookOutlined/>],["Tổng nhóm",s.groups,<TeamOutlined/>],["Đề tài chờ duyệt",s.topicsPending,<FolderOutlined/>],["Chờ phản hồi",s.progressWaiting,<BarChartOutlined/>],["Bài chờ chấm",s.waitingGrade,<BookOutlined/>]]}/><div className="dashboard-charts"><AppChartCard title="Tiến độ các nhóm" description="Tỷ lệ yêu cầu đã được chấm, tách theo lớp" empty={!hasData(data.groupProgress)}><Bar data={dataset(data.groupProgress,'% hoàn thành')} options={chartOptions(true)}/></AppChartCard><AppChartCard title="Bài nộp theo trạng thái" description="Trạng thái bài nộp trong lớp phụ trách" empty={!hasData(data.submissionsByStatus)}><Doughnut data={dataset(data.submissionsByStatus)} options={{...chartOptions(),cutout:'62%'}}/></AppChartCard><AppChartCard title="Đề tài theo trạng thái" description="Đề tài trong lớp phụ trách" empty={!hasData(data.topicsByStatus)}><Doughnut data={dataset(data.topicsByStatus)} options={{...chartOptions(),cutout:'62%'}}/></AppChartCard><AppChartCard title="Bài nộp theo tuần" description="Lượt nộp trong lớp phụ trách" empty={!hasData(data.submissionsOverTime)}><Line data={dataset(data.submissionsOverTime,'Lượt nộp')} options={chartOptions()}/></AppChartCard><AppChartCard title="Phân bố điểm nhóm" description="Điểm đã công bố quy đổi thang 10" empty={!hasData(data.gradeDistribution)}><Bar data={dataset(data.gradeDistribution,'Nhóm')} options={chartOptions()}/></AppChartCard><AppChartCard title="Hoàn thành mốc tiến độ" description="Đã hoàn thành và còn lại theo yêu cầu" empty={!data.milestoneCompletion?.length}><Bar data={{labels:(data.milestoneCompletion||[]).map(x=>x.label),datasets:[{label:'Đã hoàn thành',data:(data.milestoneCompletion||[]).map(x=>x.completed),backgroundColor:'#22A06B'},{label:'Chưa hoàn thành',data:(data.milestoneCompletion||[]).map(x=>x.remaining),backgroundColor:'#E7EAF0'}]}} options={{...chartOptions(),scales:{x:{stacked:true},y:{stacked:true,beginAtZero:true}}}}/></AppChartCard></div><div className="dashboard-secondary"><AppChartCard title="Deadline gần nhất" empty={!legacy?.upcoming?.length}>{<List dataSource={legacy?.upcoming||[]} renderItem={item=><DeadlineCard item={item}/>} />}</AppChartCard><AppChartCard title="Lớp đang phụ trách" empty={!legacy?.courseClasses?.length}><div className="course-card-grid">{(legacy?.courseClasses||[]).map(c=><CourseClassCard key={c.id} course={c}/>)}</div></AppChartCard></div></> }
function Student({ data, legacy }) { const s=data.summary||{}, progress=data.projectProgress||[], average=progress.length?Math.round(progress.reduce((a,x)=>a+Number(x.value||0),0)/progress.length):0, next=data.upcomingDeadlines?.[0]; const steps=useMemo(()=>progress.map(x=>({title:x.label,status:Number(x.value)===100?'finish':Number(x.value)>0?'process':'wait'})),[progress]); return <><Kpis items={[["Lớp đang tham gia",s.classes,<BookOutlined/>],["Nhóm hiện tại",s.groups,<TeamOutlined/>],["Tiến độ đồ án",`${average}%`,<BarChartOutlined/>],["Deadline gần nhất",next?new Date(next.deadline).toLocaleDateString('vi-VN'):'—',<BookOutlined/>],["Phản hồi mới",s.newFeedback,<UserOutlined/>]]}/><div className="student-progress"><AppChartCard title="Hành trình đồ án" description="Các mốc dựa trên yêu cầu nộp bài thực tế" empty={!steps.length}><Steps direction="vertical" items={steps}/><Progress percent={average}/></AppChartCard></div><div className="dashboard-charts"><AppChartCard title="Điểm theo tiêu chí" description="Chỉ hiển thị tiêu chí chấm đã công bố" empty={!hasData(data.gradeCriteria)}><Bar data={dataset(data.gradeCriteria,'Điểm')} options={chartOptions(true)}/></AppChartCard><AppChartCard title="Tỷ lệ công việc hoàn thành" description="Tổng hợp từ các yêu cầu thực tế" empty={!progress.length}><Progress type="circle" percent={average}/><div style={{marginTop:20}}>{progress.slice(0,6).map(x=><GroupProgressCard key={x.label} item={x}/>)}</div></AppChartCard></div><div className="dashboard-secondary"><AppChartCard title="Deadline sắp tới" empty={!data.upcomingDeadlines?.length}><List dataSource={data.upcomingDeadlines||[]} renderItem={item=><DeadlineCard item={item}/>} /></AppChartCard><AppChartCard title="Phản hồi mới nhất" empty={!data.recentFeedback?.length}><List dataSource={data.recentFeedback||[]} renderItem={item=><List.Item><List.Item.Meta title={item.title} description={item.comment||'Không có nhận xét'}/></List.Item>}/></AppChartCard></div><AppChartCard title="Lớp học phần của tôi" empty={!legacy?.courseClasses?.length}><div className="course-card-grid">{(legacy?.courseClasses||[]).map(c=><CourseClassCard key={c.id} course={c}/>)}</div></AppChartCard></> }
