import{request}from'./http'
export const listAdministrativeClasses=()=>request('/admin/administrative-classes')
export const createAdministrativeClass=data=>request('/admin/administrative-classes',{method:'POST',body:JSON.stringify(data)})
export const updateAdministrativeClass=(id,data)=>request(`/admin/administrative-classes/${id}`,{method:'PUT',body:JSON.stringify(data)})
export const listAdministrativeClassStudents=id=>request(`/admin/administrative-classes/${id}/students`)
export const listAdministrativeClassHistory=id=>request(`/admin/administrative-classes/${id}/history`)
export const removeAdministrativeClassStudent=(id,studentId,reason='Rời lớp')=>request(`/admin/administrative-classes/${id}/students/${studentId}`,{method:'DELETE',body:JSON.stringify({reason})})
export const addAdministrativeClassStudents=(id,studentIds)=>request(`/admin/administrative-classes/${id}/students`,{method:'POST',body:JSON.stringify({studentIds})})
export const transferAdministrativeClass=data=>request('/admin/administrative-classes/transfer',{method:'POST',body:JSON.stringify(data)})
export const myAdministrativeClass=()=>request('/student/administrative-class/me')
export const listEligibleClasses=id=>request(`/admin/course-classes/${id}/eligible-classes`)
export const replaceEligibleClasses=(id,administrativeClassIds)=>request(`/admin/course-classes/${id}/eligible-classes`,{method:'PUT',body:JSON.stringify({administrativeClassIds})})
export const enrollAdministrativeClasses=(id,administrativeClassIds)=>request(`/admin/course-classes/${id}/enroll-administrative-classes`,{method:'POST',body:JSON.stringify({administrativeClassIds,skipExisting:true})})
export const availableCourseClasses=()=>request('/student/course-class-enrollment/available')
export const selfEnroll=id=>request(`/student/course-class-enrollment/${id}/enroll`,{method:'POST'})
export const selfWithdraw=id=>request(`/student/course-class-enrollment/${id}/enroll`,{method:'DELETE'})
export const previewAdministrativeClassCsv=(id,file)=>{const body=new FormData();body.append('file',file);return request(`/admin/administrative-classes/${id}/import-preview`,{method:'POST',body})}
export const confirmAdministrativeClassCsv=(id,previewId)=>request(`/admin/administrative-classes/${id}/import-confirm`,{method:'POST',body:JSON.stringify({previewId})})
export const transferCourseClassEnrollment=data=>request('/admin/course-classes/transfer',{method:'POST',body:JSON.stringify(data)})
export const previewCourseEnrollment=(id,administrativeClassIds)=>request(`/admin/course-classes/${id}/enrollment-preview`,{method:'POST',body:JSON.stringify({administrativeClassIds})})
