import { useEffect, useState } from 'react'
import { Select } from 'antd'
import { addGroupMember, createGroup, getMyGroup, listGroupCandidates, removeGroupMember, transferGroupLeader } from '../../api/groupsApi'
import { listStudentCourseClasses } from '../../api/academicsApi'
import { getUser } from '../../utils/auth'
import { formatGroupName } from '../../utils/formatters'

export default function StudentGroupsPage() {
  const initialClass = new URLSearchParams(window.location.search).get('courseClassId') || ''
  const [group,setGroup]=useState(null),[classId,setClassId]=useState(initialClass),[name,setName]=useState(''),[studentId,setStudentId]=useState(undefined)
  const [classes,setClasses]=useState([]),[candidates,setCandidates]=useState([]),[loading,setLoading]=useState(true),[candidateLoading,setCandidateLoading]=useState(false),[error,setError]=useState('')
  const user=getUser()
  const load=async selectedClass=>{const value=selectedClass||classId;if(!value){setGroup(null);setLoading(false);return}setLoading(true);setError('');try{const response=await getMyGroup(value);setGroup(response.data)}catch(e){if(e.status===404)setGroup(null);else setError(e.message)}finally{setLoading(false)}}
  const loadCandidates=async(search='')=>{if(!group?.id)return;setCandidateLoading(true);try{setCandidates((await listGroupCandidates(group.id,search)).data||[])}catch(e){setError(e.message)}finally{setCandidateLoading(false)}}
  useEffect(()=>{listStudentCourseClasses({pageSize:100}).then(response=>setClasses(response.data.items||[])).catch(()=>setError('Không tải được danh sách lớp học phần.')).finally(()=>setLoading(false))},[])
  useEffect(()=>{if(initialClass)load(initialClass)},[])
  useEffect(()=>{if(group?.id)loadCandidates()},[group?.id])
  const act=async fn=>{try{setError('');await fn();setStudentId(undefined);await load()}catch(e){setError(e.message)}}
  const classOptions=classes.map(item=>({value:item.id,label:`${item.code} — ${item.subjectName}`}))
  const studentOptions=candidates.map(item=>({value:item.studentId,label:`${item.studentCode} — ${item.fullName}`,searchText:`${item.studentCode} ${item.fullName} ${item.email}`}))
  return <div><div className="page-title"><h2>Nhóm sinh viên của tôi</h2><p>Tạo nhóm và quản lý thành viên trong lớp học phần.</p></div>{error&&<div className="alert error">{error}</div>}<div className="panel group-management"><label className="form-field-ui"><span>Lớp học phần</span><Select showSearch allowClear loading={loading} optionFilterProp="label" placeholder="Chọn lớp học phần" value={classId||undefined} options={classOptions} onChange={value=>{setClassId(value||'');setGroup(null);setCandidates([]);if(value)load(value)}} /></label>{loading?<p>Đang tải...</p>:!classId?<p className="muted-text">Chọn lớp học phần để xem hoặc tạo nhóm.</p>:!group?<form onSubmit={event=>{event.preventDefault();act(()=>createGroup(classId,{name}))}}><h3>Tạo nhóm</h3><div className="form-row"><input required placeholder="Tên nhóm" value={name} onChange={event=>setName(event.target.value)}/><button className="btn-primary">Tạo nhóm</button></div></form>:<><div className="group-heading"><h3>{formatGroupName(group.name)}</h3><span>{group.memberCount}/{group.maxMembers} thành viên</span></div><p>Lớp: {group.classCode} · Trưởng nhóm: {group.leaderName}</p>{group.leaderId===Number(user?.id||user?.Id)&&<div className="group-member-picker"><label className="form-field-ui"><span>Sinh viên</span><Select showSearch allowClear filterOption={(input,option)=>(option?.searchText||'').toLowerCase().includes(input.toLowerCase())} loading={candidateLoading} placeholder="Chọn sinh viên cùng lớp" value={studentId} options={studentOptions} onSearch={loadCandidates} onChange={setStudentId} notFoundContent={candidateLoading?'Đang tìm...':'Không có sinh viên phù hợp'} /></label><button className="btn-primary" disabled={!studentId} onClick={()=>act(()=>addGroupMember(group.id,studentId))}>Thêm thành viên</button></div>}<div className="table-wrap"><table><thead><tr><th>Thành viên</th><th>MSSV</th><th>Thao tác</th></tr></thead><tbody>{group.members?.map(member=><tr key={member.studentId}><td>{member.fullName}{member.isLeader?' (Trưởng nhóm)':''}</td><td>{member.userCode}</td><td>{!member.isLeader&&group.leaderId===Number(user?.id||user?.Id)&&<><button className="btn-light" onClick={()=>act(()=>transferGroupLeader(group.id,member.studentId))}>Chuyển trưởng nhóm</button> <button className="btn-light" onClick={()=>act(()=>removeGroupMember(group.id,member.studentId))}>Xóa</button></>}</td></tr>)}</tbody></table></div></>}</div></div>
}
