import { useEffect, useState } from 'react'
import { Search } from 'lucide-react'
import { getStudentProjectsApi, getStudentRegistrationsApi, registerStudentProjectApi, cancelStudentRegistrationApi } from '../../api/studentApi'
import ConfirmModal from '../../components/common/ConfirmModal'
import { EmptyState, LoadingState, StatusBadge } from '../../components/common/UiState'

function StudentProjectsPage(){const [projects,setProjects]=useState([]),[regs,setRegs]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[search,setSearch]=useState(''),[confirm,setConfirm]=useState(null),[note,setNote]=useState(''),[saving,setSaving]=useState(false)
async function load(){try{setLoading(true);setError('');const [p,r]=await Promise.all([getStudentProjectsApi({limit:100,search}),getStudentRegistrationsApi({limit:100})]);setProjects(p?.data||[]);setRegs(r?.data||[])}catch(e){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[])
async function submit(){try{setSaving(true);setError('');if(confirm.type==='register')await registerStudentProjectApi(confirm.item.Id,note);else await cancelStudentRegistrationApi(confirm.item.Id);setSuccess(confirm.type==='register'?'Đăng ký đề tài thành công.':'Đã hủy đăng ký.');setConfirm(null);setNote('');await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
return <><div className="page-title"><h2>Đăng ký đề tài</h2><p>Khám phá đề tài đã được duyệt và theo dõi trạng thái đăng ký.</p></div>{error&&<div className="alert error">{error}</div>}{success&&<div className="alert success">{success}</div>}<div className="panel"><form className="search-bar" onSubmit={e=>{e.preventDefault();load()}}><Search size={18}/><input aria-label="Tìm đề tài" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm theo tên hoặc mô tả đề tài..."/><button className="btn-primary small">Tìm kiếm</button></form></div><section className="panel"><h3>Đăng ký của tôi</h3>{regs.length?regs.map(r=><div className="registration-row" key={r.Id}><div><strong>{r.Title}</strong><span>GVHD: {r.TeacherName||'-'}</span>{r.ReviewNote&&<p className="review-note">Phản hồi: {r.ReviewNote}</p>}</div><div className="row-actions"><StatusBadge status={r.Status}/>{r.Status==='Pending'&&<button className="btn-danger" onClick={()=>setConfirm({type:'cancel',item:r})}>Hủy đăng ký</button>}</div></div>):<EmptyState title="Bạn chưa đăng ký đề tài" description="Chọn một đề tài phù hợp ở danh sách bên dưới."/>}</section>{loading?<LoadingState/>:projects.length?<div className="project-grid">{projects.map(p=><article className="project-card" key={p.Id}><div className="project-card-header"><StatusBadge status={p.Status}/><span>{p.ApprovedStudents||0}/{p.MaxStudents||1} sinh viên</span></div><h3>{p.Title}</h3><p>{p.Description||'Chưa có mô tả.'}</p><div className="project-meta"><span><strong>Giảng viên:</strong> {p.TeacherName||p.AdvisorTeacherName||'-'}</span><span><strong>Yêu cầu:</strong> {p.Requirements||'-'}</span></div><button className="btn-primary small" disabled={regs.some(r=>['Pending','Approved'].includes(r.Status))} onClick={()=>setConfirm({type:'register',item:p})}>Đăng ký đề tài</button></article>)}</div>:<EmptyState title="Chưa có đề tài khả dụng" description="Hiện chưa có đề tài nào đang mở đăng ký."/>}<ConfirmModal open={Boolean(confirm)} title={confirm?.type==='register'?'Xác nhận đăng ký đề tài?':'Hủy đăng ký đề tài?'} description={confirm?.type==='register'?`Bạn đang đăng ký đề tài “${confirm?.item?.Title}”. Yêu cầu sẽ được gửi tới giảng viên xét duyệt.`:'Đăng ký đang chờ duyệt sẽ bị hủy.'} confirmLabel={confirm?.type==='register'?'Gửi đăng ký':'Hủy đăng ký'} loading={saving} onClose={()=>setConfirm(null)} onConfirm={submit}/>{confirm?.type==='register'&&<div className="modal-note"><label htmlFor="registration-note">Ghi chú với giảng viên</label><textarea id="registration-note" value={note} onChange={e=>setNote(e.target.value)} /></div>}</>}
export default StudentProjectsPage
