SET XACT_ABORT ON;
BEGIN TRY
  BEGIN TRANSACTION;
  IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name='CK_RequiredSubmissionItems_Type')
    ALTER TABLE dbo.RequiredSubmissionItems DROP CONSTRAINT CK_RequiredSubmissionItems_Type;
  ALTER TABLE dbo.RequiredSubmissionItems ADD CONSTRAINT CK_RequiredSubmissionItems_Type CHECK (ItemType IN (
    'TEXT','REPORT','SLIDE','SOURCE_CODE','FILE','GITHUB_LINK','JIRA_LINK','FIGMA_LINK','VIDEO_LINK',
    'DEMO_LINK','DOCUMENT_LINK','OTHER_LINK','OTHER','TEXT_SUMMARY','COMPLETED_TASKS','BLOCKERS',
    'NEXT_PLAN','GITHUB_REPOSITORY','GITHUB_PULL_REQUEST','JIRA_BOARD','FIGMA','DEMO_VIDEO',
    'REPORT_FILE','OTHER_URL'
  ));
  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
  THROW;
END CATCH;
