SET XACT_ABORT ON; BEGIN TRANSACTION;
CREATE TABLE Notifications(Id INT IDENTITY PRIMARY KEY,UserId INT NOT NULL,Type NVARCHAR(50) NOT NULL,Title NVARCHAR(200) NOT NULL,Message NVARCHAR(1000) NOT NULL,RelatedEntityType NVARCHAR(50) NULL,RelatedEntityId INT NULL,EventKey NVARCHAR(200) NOT NULL,IsRead BIT NOT NULL DEFAULT 0,CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),ReadAt DATETIME2 NULL,FOREIGN KEY(UserId) REFERENCES Users(Id),UNIQUE(UserId,EventKey));
CREATE INDEX IX_Notifications_User_Unread ON Notifications(UserId,IsRead,CreatedAt DESC);CREATE INDEX IX_Notifications_User_Created ON Notifications(UserId,CreatedAt DESC);
COMMIT TRANSACTION;
