import { useState } from 'react'
import { NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { BarChart3, BookOpen, ChevronDown, FileText, GraduationCap, KeyRound, Layers3, LogOut, Menu, PanelLeftClose, PanelLeftOpen, School, Search, User, UserPlus, Users, X } from 'lucide-react'
import { USER_ROLES } from '../constants/roles'
import { clearAuth, getUser, getUserRole } from '../utils/auth'
import NotificationBell from '../components/NotificationBell'
import PrivateFooter from '../components/PrivateFooter'

const roleText = { ADMIN: 'Quản trị viên', LECTURER: 'Giảng viên', STUDENT: 'Sinh viên' }
const adminSections = [
  { title: 'Tổng quan', items: [{ label: 'Tổng quan', path: '/admin/dashboard', icon: BarChart3 }] },
  { title: 'Người dùng', items: [{ label: 'Danh sách tài khoản', path: '/admin/users', icon: Users }, { label: 'Thêm tài khoản', path: '/admin/users/new', icon: UserPlus }, { label: 'Nhập sinh viên', path: '/admin/students/import', icon: FileText }, { label: 'Nhập giảng viên', path: '/admin/lecturers/import', icon: GraduationCap }] },
  { title: 'Học vụ', items: [{ label: 'Năm học', path: '/admin/academic-years', icon: Layers3 }, { label: 'Học kỳ', path: '/admin/semesters', icon: BookOpen }, { label: 'Môn học', path: '/admin/subjects', icon: School }, { label: 'Lớp học phần', path: '/admin/course-classes', icon: GraduationCap }] },
  { title: 'Hệ thống', items: [{ label: 'Hồ sơ cá nhân', path: '/profile', icon: User }, { label: 'Đổi mật khẩu', path: '/change-password', icon: KeyRound }] },
]
const lecturerMain = [['Trang chủ','/lecturer/dashboard'],['Bảng điều khiển','/lecturer/dashboard'],['Lớp phụ trách','/lecturer/course-classes'],['Nhóm & Đề tài','/lecturer/groups'],['Bài nộp','/lecturer/submissions'],['Chấm điểm','/lecturer/submissions']]
const studentMain = [['Trang chủ','/student/dashboard'],['Bảng điều khiển','/student/dashboard'],['Các lớp học của tôi','/student/course-classes'],['Nhóm của tôi','/student/groups/my-group'],['Bài nộp','/student/submissions'],['Kết quả','/student/submissions']]
const extras = { LECTURER:[['Vòng đăng ký đề tài','/lecturer/topic-registration-rounds'],['Tiến độ tuần','/lecturer/progress'],['Yêu cầu nộp','/lecturer/submission-requirements'],['Đề tài chờ duyệt','/lecturer/topic-registrations']], STUDENT:[['Vòng đăng ký đề tài','/student/topic-rounds'],['Tiến độ tuần','/student/progress'],['Đề tài','/student/topic-registration'],['Yêu cầu nộp','/student/submission-requirements']] }

function AccountMenu({ name, role, logout }) {
  const [open,setOpen]=useState(false)
  return <div className="account-menu"><button className="account-trigger" onClick={()=>setOpen(!open)} aria-expanded={open}><span className="lms-avatar">{name.charAt(0).toUpperCase()}</span><span className="account-copy"><strong>{name}</strong><small>{roleText[role]}</small></span><ChevronDown size={16}/></button>{open&&<div className="account-dropdown"><NavLink to="/profile" onClick={()=>setOpen(false)}><User size={17}/> Hồ sơ</NavLink><NavLink to="/change-password" onClick={()=>setOpen(false)}><KeyRound size={17}/> Đổi mật khẩu</NavLink><button onClick={logout}><LogOut size={17}/> Đăng xuất</button></div>}</div>
}
function LmsLayout({ role,name,logout }) {
  const [mobileOpen,setMobileOpen]=useState(false),[moreOpen,setMoreOpen]=useState(false),main=role===USER_ROLES.LECTURER?lecturerMain:studentMain
  return <div className="lms-shell private-app"><header className="lms-topbar"><div className="lms-topbar-inner"><button className="lms-mobile-toggle" onClick={()=>setMobileOpen(!mobileOpen)} aria-label="Mở menu">{mobileOpen?<X/>:<Menu/>}</button><NavLink className="lms-brand" to={main[0][1]}><span>TVU</span><div><strong>Student Project Portal</strong><small>Cổng học tập và dự án</small></div></NavLink><nav className={`lms-nav ${mobileOpen?'open':''}`}>{main.map(([label,path],index)=><NavLink key={`${label}-${index}`} to={path} onClick={()=>setMobileOpen(false)} className={({isActive})=>isActive?'active':''}>{label}</NavLink>)}<div className="more-nav"><button onClick={()=>setMoreOpen(!moreOpen)}>Xem thêm <ChevronDown size={15}/></button>{moreOpen&&<div className="more-dropdown">{extras[role].map(([label,path])=><NavLink key={label} to={path} onClick={()=>{setMoreOpen(false);setMobileOpen(false)}}>{label}</NavLink>)}<NavLink to="/profile">Thông báo</NavLink><NavLink to="/profile">Hồ sơ</NavLink></div>}</div></nav><div className="lms-user-actions"><NotificationBell role={role}/><AccountMenu name={name} role={role} logout={logout}/></div></div></header><main className="lms-content private-main"><Outlet/></main><PrivateFooter/></div>
}
const crumbLabels = {dashboard:'Tổng quan',users:'Người dùng','academic-years':'Năm học',semesters:'Học kỳ',subjects:'Môn học','course-classes':'Lớp học phần','students':'Sinh viên','lecturers':'Giảng viên',import:'Nhập danh sách',profile:'Hồ sơ'}
function AdminLayout({ name,role,logout }) {
  const navigate=useNavigate(),location=useLocation(),[mobileOpen,setMobileOpen]=useState(false),[collapsed,setCollapsed]=useState(false),[accountOpen,setAccountOpen]=useState(false)
  const segments=location.pathname.split('/').filter(Boolean).slice(1),current=segments.at(-1)||'dashboard'
  const quickNavigate=event=>{if(event.key!=='Enter')return;const term=event.currentTarget.value.trim().toLocaleLowerCase('vi-VN');const target=adminSections.flatMap(section=>section.items).find(item=>item.label.toLocaleLowerCase('vi-VN').includes(term));if(target)navigate(target.path)}
  const link=item=>{const Icon=item.icon;return <NavLink key={`${item.path}-${item.label}`} title={collapsed?item.label:undefined} to={item.path} onClick={()=>setMobileOpen(false)} className={({isActive})=>isActive?'menu-link active':'menu-link'}><Icon size={19}/><span>{item.label}</span></NavLink>}
  return <div className={`app-shell admin-modern-shell ${collapsed?'sidebar-collapsed':''}`}><aside className={`sidebar ${mobileOpen?'open':''}`}><div className="brand" onClick={()=>navigate('/admin/dashboard')}><div className="brand-logo">TVU</div><div className="brand-text"><h2>Cổng dự án</h2><p>Đại học Trà Vinh</p></div><button className="mobile-close" onClick={event=>{event.stopPropagation();setMobileOpen(false)}}><X/></button></div><nav className="menu">{adminSections.map(section=><section className="menu-section" key={section.title}><p>{section.title}</p>{section.items.map(link)}</section>)}</nav><button className="sidebar-collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}<span>Thu gọn menu</span></button></aside>{mobileOpen&&<button className="sidebar-backdrop" aria-label="Đóng menu" onClick={()=>setMobileOpen(false)}/>}<div className="main-area private-app"><header className="header"><div className="header-leading"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}><Menu/></button><div><h1>{crumbLabels[current]||'Khu vực quản trị'}</h1><div className="breadcrumbs"><span>Quản trị</span><i>/</i><strong>{crumbLabels[current]||'Trang hiện tại'}</strong></div></div></div><label className="admin-quick-search"><Search size={17}/><input placeholder="Tìm nhanh chức năng..." aria-label="Tìm nhanh" onKeyDown={quickNavigate}/></label><div className="header-user"><NotificationBell role={role}/><div className="admin-account"><button className="admin-account-trigger" onClick={()=>setAccountOpen(!accountOpen)}><span className="avatar">{name.charAt(0).toUpperCase()}</span><span className="user-info"><strong>{name}</strong><small>Quản trị viên</small></span><ChevronDown size={15}/></button>{accountOpen&&<div className="admin-account-dropdown"><NavLink to="/profile" onClick={()=>setAccountOpen(false)}><User size={17}/>Hồ sơ cá nhân</NavLink><NavLink to="/change-password" onClick={()=>setAccountOpen(false)}><KeyRound size={17}/>Đổi mật khẩu</NavLink><button onClick={logout}><LogOut size={17}/>Đăng xuất</button></div>}</div></div></header><main className="content private-main"><Outlet/></main><PrivateFooter/></div></div>
}
export default function MainLayout(){const navigate=useNavigate(),user=getUser(),role=getUserRole(),name=user?.fullName||user?.FullName||user?.email||user?.Email||'Người dùng',logout=()=>{clearAuth();navigate('/login')};return role===USER_ROLES.ADMIN?<AdminLayout name={name} role={role} logout={logout}/>:<LmsLayout name={name} role={role} logout={logout}/>}
