import * as repo from './courseClassLecturers.repository.js'
const roles=new Set(['PRIMARY','CO_LECTURER']),result=(success,statusCode,message,data=null)=>({success,statusCode,message,data}),id=v=>Number.isInteger(Number(v))&&Number(v)>0?Number(v):null
const normalize=x=>({lecturerId:id(x?.lecturerId),assignmentRole:String(x?.assignmentRole||'').toUpperCase(),isActive:x?.isActive===undefined?true:x.isActive})
const decorate=x=>({...x,assignmentRoleLabel:x.assignmentRole==='PRIMARY'?'Giảng viên chính':'Giảng viên phối hợp'})
async function context(value){const key=id(value);if(!key)return[result(false,400,'Mã lớp học phần không hợp lệ')];if(!await repo.findClass(key))return[result(false,404,'Không tìm thấy lớp học phần')];return[null,key]}
const invalid=x=>!x.lecturerId?'Giảng viên không hợp lệ.':!roles.has(x.assignmentRole)?'Vai trò phân công không hợp lệ.':typeof x.isActive!=='boolean'?'Trạng thái không hợp lệ.':null
export async function list(classId){const[e,key]=await context(classId);return e||result(true,200,'Lấy danh sách giảng viên thành công',(await repo.list(key)).map(decorate))}
export async function assign(classId,body,userId){const[e,key]=await context(classId);if(e)return e;const item=normalize(body),message=invalid(item);if(message)return result(false,400,message);if(!await repo.findLecturer(item.lecturerId))return result(false,400,'Tài khoản giảng viên không tồn tại hoặc không hoạt động');if(await repo.find(key,item.lecturerId))return result(false,409,'Giảng viên đã được phân công vào lớp');if(item.assignmentRole==='PRIMARY'&&await repo.activePrimary(key))return result(false,409,'Lớp đã có giảng viên chính');return result(true,201,'Phân công giảng viên thành công',decorate(await repo.insert(key,item,userId)))}
export async function update(classId,lecturerId,body){const[e,key]=await context(classId);if(e)return e;const lecturer=id(lecturerId),current=lecturer&&await repo.find(key,lecturer);if(!current)return result(false,404,'Không tìm thấy phân công');const item=normalize({...current,...body}),message=invalid(item);if(message)return result(false,400,message);if(item.assignmentRole==='PRIMARY'&&item.isActive&&await repo.activePrimary(key,lecturer))return result(false,409,'Lớp đã có giảng viên chính');return result(true,200,'Cập nhật phân công thành công',decorate(await repo.update(key,lecturer,item)))}
export async function remove(classId,lecturerId){const[e,key]=await context(classId);if(e)return e;const lecturer=id(lecturerId);if(!lecturer||!await repo.remove(key,lecturer))return result(false,404,'Không tìm thấy phân công');return result(true,200,'Đã gỡ phân công giảng viên')}
export async function bulk(classId,body,userId){const[e,key]=await context(classId);if(e)return e;const items=Array.isArray(body?.lecturers)?body.lecturers.map(normalize):[];if(new Set(items.map(x=>x.lecturerId)).size!==items.length)return result(false,409,'Danh sách có giảng viên trùng lặp');if(items.filter(x=>x.assignmentRole==='PRIMARY'&&x.isActive).length>1)return result(false,409,'Mỗi lớp chỉ có tối đa một giảng viên chính');for(const item of items){const message=invalid(item);if(message)return result(false,400,message)}try{return result(true,200,'Cập nhật danh sách giảng viên thành công',(await repo.replace(key,items,userId)).map(decorate))}catch(error){if(error.code==='LECTURER_INVALID')return result(false,400,'Có giảng viên không tồn tại hoặc không hoạt động');throw error}}
