import * as repo from'./grading.repository.js';import * as submissionRepo from'../submissions/submissions.repository.js';import{validateGrade}from'./grading.validation.js';const MAX=10,ok=(data,message,statusCode=200)=>({success:true,data,message,statusCode}),fail=(statusCode,message,errors=null)=>({success:false,statusCode,message,errors}),id=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null},text=v=>String(v??'').trim();
async function owned(submissionId,user){const s=await repo.submission(id(submissionId));if(!s)return{error:fail(404,'Không tìm thấy bài nộp')};if(s.lecturerId!==user.id)return{error:fail(403,'Bạn không phụ trách lớp học phần này')};if(!s.latestAttemptNumber)return{error:fail(409,'Bài chưa có lần nộp')};return{s}}
export async function getCriteria(requirementId,user){const rid=id(requirementId),owner=await repo.requirementOwner(rid);if(!owner)return fail(404,'Không tìm thấy yêu cầu nộp');if(owner.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp này');return ok(await repo.criteria(rid),'Lấy tiêu chí thành công')}
function criterionPayload(b){return{name:text(b.name),description:text(b.description),maxScore:Number(b.maxScore),displayOrder:Number.isInteger(Number(b.displayOrder))?Number(b.displayOrder):0}}
export async function createCriterion(requirementId,b,user){const rid=id(requirementId),owner=await repo.requirementOwner(rid),d=criterionPayload(b);if(!owner)return fail(404,'Không tìm thấy yêu cầu');if(owner.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp này');if(!d.name||!Number.isFinite(d.maxScore)||d.maxScore<=0)return fail(400,'Tên và điểm tối đa hợp lệ là bắt buộc');const existing=await repo.criteria(rid);if(existing.reduce((n,x)=>n+Number(x.maxScore),0)+d.maxScore>MAX)return fail(400,`Tổng điểm tiêu chí không vượt ${MAX}`);return ok(await repo.createCriterion({...d,requirementId:rid}),'Tạo tiêu chí thành công',201)}
export async function updateCriterion(cid,b,user){const current=await repo.criterion(id(cid));if(!current)return fail(404,'Không tìm thấy tiêu chí');if(current.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp này');const d=criterionPayload(b);if(!d.name||!Number.isFinite(d.maxScore)||d.maxScore<=0)return fail(400,'Tiêu chí không hợp lệ');const all=await repo.criteria(current.requirementId),other=all.filter(x=>x.id!==current.id).reduce((n,x)=>n+Number(x.maxScore),0);if(other+d.maxScore>MAX)return fail(400,`Tổng điểm tiêu chí không vượt ${MAX}`);return ok(await repo.updateCriterion(current.id,d),'Cập nhật tiêu chí thành công')}
export async function deleteCriterion(cid,user){const c=await repo.criterion(id(cid));if(!c)return fail(404,'Không tìm thấy tiêu chí');if(c.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp này');return await repo.deleteCriterion(c.id)?ok(null,'Xóa tiêu chí thành công'):fail(409,'Tiêu chí đã được dùng để chấm điểm')}
export async function review(submissionId,user){const a=await owned(submissionId,user);return a.error||ok({...await repo.review(a.s.id),attempts:await submissionRepo.attempts(a.s.id),criteria:await repo.criteria(a.s.requirementId)},'Lấy dữ liệu chấm điểm thành công')}
export async function status(submissionId,b,user){const a=await owned(submissionId,user);if(a.error)return a.error;const next=text(b.status).toUpperCase();if(!['UNDER_REVIEW','REQUIRES_REVISION'].includes(next))return fail(400,'Trạng thái review không hợp lệ');if(next==='REQUIRES_REVISION'&&!text(b.comment))return fail(400,'Phải nhập lý do yêu cầu chỉnh sửa');return ok(await repo.setStatus(a.s,next,text(b.comment),user.id),'Cập nhật trạng thái thành công')}
export async function feedback(submissionId,b,user){const a=await owned(submissionId,user);if(a.error)return a.error;const d={comment:text(b.comment),revisionRequired:Boolean(b.revisionRequired),revisionReason:text(b.revisionReason)};if(d.revisionRequired&&!d.revisionReason)return fail(400,'Phải nhập lý do yêu cầu chỉnh sửa');return ok(await repo.saveFeedback(a.s,d,user.id),'Lưu nhận xét thành công')}
export async function grade(submissionId,b,user){const a=await owned(submissionId,user);if(a.error)return a.error;if(!['SUBMITTED','LATE','RESUBMITTED','UNDER_REVIEW','REQUIRES_REVISION','GRADED'].includes(a.s.status))return fail(409,'Trạng thái bài nộp không thể chấm');const current=await repo.review(a.s.id);if(current.grade?.isPublished)return fail(409,'Điểm đã công bố không thể chỉnh sửa');const criteria=await repo.criteria(a.s.requirementId),v=validateGrade(criteria,b);if(v.error)return fail(400,v.error);return ok(await repo.saveGrade(a.s,{...v,maxScore:MAX,isPublished:Boolean(b.isPublished)},user.id),b.isPublished?'Công bố điểm thành công':'Lưu điểm nháp thành công')}
async function studentAccess(submissionId,user){const s=await repo.submission(id(submissionId));if(!s||!await repo.member(s.groupId,user.id))return{error:fail(404,'Không tìm thấy kết quả của nhóm')};return{s}}
export async function result(submissionId,user){const a=await studentAccess(submissionId,user);if(a.error)return a.error;const r=await repo.review(a.s.id);if(r.grade&&!r.grade.isPublished)r.grade=null;const now=Date.now(),within=now>=new Date(a.s.startAt).getTime()&&(now<=new Date(a.s.deadline).getTime()||a.s.allowLate);r.canResubmit=a.s.status==='REQUIRES_REVISION'&&a.s.roundStatus==='OPEN'&&a.s.allowResubmission&&a.s.latestAttemptNumber<a.s.maxAttempts&&within;return ok(r,'Lấy kết quả chấm điểm thành công')}
export async function studentFeedback(submissionId,user){const r=await result(submissionId,user);return r.success?ok(r.data.feedback,'Lấy nhận xét thành công'):r}
export async function studentHistory(submissionId,user){const r=await result(submissionId,user);return r.success?ok(r.data.history,'Lấy lịch sử review thành công'):r}
