import * as repo from'./submissions.repository.js';import{notifyUsers}from'../notifications/notifications.service.js';import{cleanupFiles,relativeUploadPath,resolveStoredFile}from'../../services/fileStorage.service.js';
const ok=(data,message,statusCode=200)=>({success:true,data,message,statusCode}),fail=(statusCode,message)=>({success:false,statusCode,message}),idOf=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null};
function url(value){const v=String(value||'').trim();if(!v)return null;try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
async function access(id,user){const s=await repo.findSubmission(idOf(id));if(!s)return{error:fail(404,'Không tìm thấy bài nộp')};if(user.role==='LECTURER')return s.lecturerId===user.id?{submission:s}:{error:fail(403,'Bạn không phụ trách lớp này')};return await repo.isGroupMember(s.groupId,user.id)?{submission:s}:{error:fail(403,'Bạn không thuộc nhóm nộp bài này')}}
export async function current(requirementId,user){const ctx=await repo.studentContext(idOf(requirementId),user.id);if(!ctx)return fail(404,'Không tìm thấy yêu cầu hoặc nhóm trong lớp');const s=await repo.findByRequirementGroup(ctx.requirementId,ctx.groupId);return ok({requirement:ctx,submission:s?s:null,attempts:s?await repo.attempts(s.id):[]},'Lấy bài nộp thành công')}
export async function submit(requirementId,body,files,user){const ctx=await repo.studentContext(idOf(requirementId),user.id);if(!ctx){await cleanupFiles(files);return fail(404,'Không tìm thấy yêu cầu hoặc nhóm trong lớp')}const now=Date.now(),start=new Date(ctx.startAt).getTime(),deadline=new Date(ctx.deadline).getTime();if(ctx.roundStatus!=='OPEN'||now<start){await cleanupFiles(files);return fail(409,'Đợt nộp chưa mở')}const late=now>deadline;if(late&&!ctx.allowLate){await cleanupFiles(files);return fail(409,'Đã quá hạn nộp')}const existing=await repo.findByRequirementGroup(ctx.requirementId,ctx.groupId),attempts=existing?.latestAttemptNumber||0;if(attempts&&!ctx.allowResubmission){await cleanupFiles(files);return fail(409,'Đợt nộp không cho phép nộp lại')}if(attempts>=ctx.maxAttempts){await cleanupFiles(files);return fail(409,'Đã đạt số lần nộp tối đa')}const fileTypes=files.map(f=>f.fieldname),github=url(body.githubUrl),video=url(body.videoUrl);if(body.githubUrl&&!github||body.videoUrl&&!video){await cleanupFiles(files);return fail(400,'GitHub hoặc video URL không hợp lệ')}const supplied=new Set([...fileTypes,...(github?['GITHUB_LINK']:[]),...(video?['VIDEO_LINK']:[])]);if([...supplied].some(t=>!ctx.requiredItems.includes(t))||ctx.requiredItems.some(t=>!supplied.has(t))){await cleanupFiles(files);return fail(400,'Phải nộp đúng và đủ các loại nội dung được yêu cầu')}const max=(ctx.maxFileSizeMb||20)*1024*1024;if(files.some(f=>f.size>max)){await cleanupFiles(files);return fail(413,`Mỗi file không được vượt quá ${ctx.maxFileSizeMb||20} MB`)}const metadata=files.map(f=>({type:f.fieldname,originalName:f.originalname,storedName:f.filename,relativePath:relativeUploadPath(f.filename),mimeType:f.mimetype,size:f.size})),links=[...(github?[{type:'GITHUB_LINK',url:github}]:[]),...(video?[{type:'VIDEO_LINK',url:video}]:[])];try{const s=await repo.createAttempt(ctx,user.id,metadata,links,late);await notifyUsers([ctx.lecturerId],{type:'SUBMISSION_RECEIVED',title:'Có bài nộp mới',message:'Nhóm '+ctx.groupName+' đã nộp bài.',relatedEntityType:'SUBMISSION',relatedEntityId:s.id,eventKey:'SUBMISSION_ATTEMPT:'+s.id+':'+s.latestAttemptNumber});return ok({...s,attempts:await repo.attempts(s.id)},late?'Nộp bài trễ thành công':'Nộp bài thành công',201)}catch(e){await cleanupFiles(files);throw e}}
export async function detail(id,user){const a=await access(id,user);return a.error||ok({...a.submission,attempts:await repo.attempts(a.submission.id)},'Lấy chi tiết bài nộp thành công')}
export async function getHistory(id,user){const a=await access(id,user);return a.error||ok(await repo.history(a.submission.id),'Lấy lịch sử nộp thành công')}
export async function attempt(id,attemptId,user){const a=await access(id,user);if(a.error)return a.error;const item=(await repo.attempts(a.submission.id)).find(x=>x.id===idOf(attemptId));return item?ok(item,'Lấy lần nộp thành công'):fail(404,'Không tìm thấy lần nộp')}
export async function lecturerList(requirementId,user){return ok(await repo.lecturerRequirementSubmissions(idOf(requirementId),user.id),'Lấy danh sách bài nộp thành công')}
export async function download(fileId,user){const f=await repo.findFile(idOf(fileId));if(!f)return{error:fail(404,'Không tìm thấy file')};const allowed=user.role==='LECTURER'?f.lecturerId===user.id:await repo.isGroupMember(f.groupId,user.id);if(!allowed)return{error:fail(403,'Bạn không có quyền tải file này')};try{return{file:f,fullPath:resolveStoredFile(f.relativePath)}}catch{return{error:fail(400,'Đường dẫn file không hợp lệ')}}}
