import * as repo from './submissionRequirements.repository.js';
import { notifyClass } from '../notifications/notifications.service.js';
const TYPES=['TEXT','REPORT','SLIDE','SOURCE_CODE','FILE','GITHUB_LINK','JIRA_LINK','FIGMA_LINK','VIDEO_LINK','DEMO_LINK','DOCUMENT_LINK','OTHER_LINK','OTHER'],STATUSES=['DRAFT','OPEN','CLOSED','CANCELLED'];
const ok=(data,message,statusCode=200)=>({success:true,data,message,statusCode}),fail=(statusCode,message,errors=null)=>({success:false,statusCode,message,errors});
const idOf=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null},clean=v=>String(v??'').trim();
function effective(x){const now=Date.now(),start=new Date(x.startAt).getTime(),end=new Date(x.deadline).getTime();if(x.status!=='OPEN')return x.status;if(now<start)return'SCHEDULED';if(now>end)return x.allowLate?'OPEN_LATE':'EXPIRED';return'OPEN';}
const decorate=x=>({...x,effectiveStatus:effective(x)});
function payload(b){const items=Array.isArray(b.requiredItems)?b.requiredItems.map(x=>typeof x==='string'?{type:x}:{type:clean(x.type).toUpperCase(),description:clean(x.description)}):[];return{classId:idOf(b.classId),title:clean(b.title),description:clean(b.description),instructions:clean(b.instructions),startAt:new Date(b.startAt),deadline:new Date(b.deadline),allowLate:Boolean(b.allowLate),allowResubmission:Boolean(b.allowResubmission),maxAttempts:Number(b.maxAttempts),maxFileSizeMb:b.maxFileSizeMb===null||b.maxFileSizeMb===''||b.maxFileSizeMb===undefined?null:Number(b.maxFileSizeMb),requirementType:clean(b.requirementType||'ASSIGNMENT').toUpperCase(),weekNumber:b.weekNumber===''||b.weekNumber===null||b.weekNumber===undefined?null:Number(b.weekNumber),requiredItems:items};}
function validate(d){const e={};if(!['ASSIGNMENT','WEEKLY_PROGRESS'].includes(d.requirementType))e.requirementType=['Loại yêu cầu không hợp lệ.'];if(d.requirementType==='WEEKLY_PROGRESS'&&(!Number.isInteger(d.weekNumber)||d.weekNumber<1||d.weekNumber>53))e.weekNumber=['Tuần phải từ 1 đến 53.'];if(!d.classId)e.classId=['Lớp học phần không hợp lệ.'];if(!d.title)e.title=['Tên yêu cầu là bắt buộc.'];if(!d.description)e.description=['Mô tả là bắt buộc.'];if(Number.isNaN(d.startAt.getTime())||Number.isNaN(d.deadline.getTime())||d.startAt>=d.deadline)e.time=['Thời gian bắt đầu phải trước hạn nộp.'];if(!Number.isInteger(d.maxAttempts)||d.maxAttempts<1)e.maxAttempts=['Số lần nộp phải lớn hơn 0.'];if(d.maxFileSizeMb!==null&&(!Number.isInteger(d.maxFileSizeMb)||d.maxFileSizeMb<1))e.maxFileSizeMb=['Dung lượng tối đa phải lớn hơn 0.'];if(new Set(d.requiredItems.map(x=>x.type)).size!==d.requiredItems.length||d.requiredItems.some(x=>!TYPES.includes(x.type)))e.requiredItems=['Loại nội dung bắt buộc không hợp lệ hoặc bị trùng.'];return e;}
async function owned(id,user){const item=await repo.findById(idOf(id));if(!item)return{error:fail(404,'Không tìm thấy yêu cầu nộp')};return item.lecturerId===user.id?{item}:{error:fail(403,'Bạn không phụ trách lớp học phần này')};}
export async function listLecturer(user){return ok((await repo.listForLecturer(user.id)).map(decorate),'Lấy danh sách yêu cầu thành công');}
export async function detailLecturer(id,user){const a=await owned(id,user);return a.error||ok(decorate(a.item),'Lấy chi tiết yêu cầu thành công');}
export async function create(b,user){const d=payload(b),errors=validate(d);if(Object.keys(errors).length)return fail(400,'Dữ liệu không hợp lệ',errors);const cls=await repo.findClass(d.classId);if(!cls)return fail(404,'Không tìm thấy lớp học phần');if(cls.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp học phần này');try{const created=decorate(await repo.create({...d,userId:user.id}));await notifyClass(d.classId,{type:'SUBMISSION_REQUIREMENT_CREATED',title:'Có yêu cầu nộp mới',message:'Giảng viên đã tạo yêu cầu '+d.title+'.',relatedEntityType:'SUBMISSION_REQUIREMENT',relatedEntityId:created.id,eventKey:'REQUIREMENT_CREATED:'+created.id});return ok(created,'Tạo yêu cầu nộp thành công',201)}catch(e){if([2601,2627].includes(e.number))return fail(409,'Tên yêu cầu đã tồn tại trong lớp');throw e}}
export async function update(id,b,user){const a=await owned(id,user);if(a.error)return a.error;if(['CLOSED','CANCELLED'].includes(a.item.status))return fail(409,'Không thể sửa yêu cầu đã đóng hoặc hủy');const d=payload({...b,classId:a.item.classId}),errors=validate(d);if(Object.keys(errors).length)return fail(400,'Dữ liệu không hợp lệ',errors);return ok(decorate(await repo.update(a.item.id,d)),'Cập nhật yêu cầu thành công');}
export async function status(id,b,user){const a=await owned(id,user);if(a.error)return a.error;const s=clean(b.status).toUpperCase();if(!STATUSES.includes(s))return fail(400,'Trạng thái không hợp lệ');if(s==='OPEN'&&!a.item.requiredItems.length)return fail(409,'Không thể mở đợt nộp thiếu nội dung bắt buộc');if(a.item.status==='CLOSED'&&s!=='CLOSED')return fail(409,'Đợt đã đóng không thể mở lại');const updated=decorate(await repo.setStatus(a.item.id,s));if(s==='OPEN')await notifyClass(a.item.classId,{type:'SUBMISSION_ROUND_OPENED',title:'Đợt nộp đã mở',message:'Yêu cầu '+a.item.title+' đã mở nhận bài.',relatedEntityType:'SUBMISSION_REQUIREMENT',relatedEntityId:a.item.id,eventKey:'REQUIREMENT_OPENED:'+a.item.id});return ok(updated,'Cập nhật trạng thái thành công');}
export async function remove(id,user){const a=await owned(id,user);if(a.error)return a.error;return await repo.softDelete(a.item.id)?ok(null,'Xóa yêu cầu thành công'):fail(409,'Chỉ được xóa yêu cầu nháp hoặc đã hủy');}
export async function listStudent(user){return ok((await repo.listForStudent(user.id)).map(decorate),'Lấy danh sách yêu cầu thành công');}
export async function detailStudent(id,user){const items=await repo.listForStudent(user.id),item=items.find(x=>x.id===idOf(id));return item?ok(decorate(item),'Lấy chi tiết yêu cầu thành công'):fail(404,'Không tìm thấy yêu cầu nộp trong lớp của bạn');}
