import{access as fileAccess}from'node:fs/promises';import * as repo from'./submissions.repository.js';import{notifyUsers}from'../notifications/notifications.service.js';import{cleanupFiles,relativeUploadPath,resolveStoredFile}from'../../services/fileStorage.service.js';
const ok=(data,message,statusCode=200)=>({success:true,data,message,statusCode}),fail=(statusCode,message)=>({success:false,statusCode,message}),idOf=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null};
function url(value){const v=String(value||'').trim();if(!v)return null;try{const u=new URL(v);return['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
async function access(id,user){const s=await repo.findSubmission(idOf(id));if(!s)return{error:fail(404,'Không tìm thấy bài nộp')};if(user.role==='LECTURER')return s.lecturerId===user.id?{submission:s}:{error:fail(403,'Bạn không phụ trách lớp này')};return await repo.isGroupMember(s.groupId,user.id)?{submission:s}:{error:fail(403,'Bạn không thuộc nhóm nộp bài này')}}
export async function current(requirementId,user){const ctx=await repo.studentContext(idOf(requirementId),user.id);if(!ctx)return fail(404,'Không tìm thấy yêu cầu hoặc nhóm trong lớp');const s=await repo.findByRequirementGroup(ctx.requirementId,ctx.groupId);return ok({requirement:ctx,submission:s?s:null,attempts:s?await repo.attempts(s.id):[]},'Lấy bài nộp thành công')}
export async function submit(requirementId,body,files,user){
 const ctx=await repo.studentContext(idOf(requirementId),user.id);if(!ctx){await cleanupFiles(files);return fail(404,'Không tìm thấy yêu cầu hoặc nhóm trong lớp')}
 if(ctx.requirementType==='WEEKLY_PROGRESS'&&ctx.leaderId!==user.id){await cleanupFiles(files);return fail(403,'Chỉ trưởng nhóm được nộp tiến độ tuần')}
 const now=Date.now(),start=new Date(ctx.startAt).getTime(),deadline=new Date(ctx.deadline).getTime();if(ctx.roundStatus!=='OPEN'||now<start){await cleanupFiles(files);return fail(409,'Đợt nộp chưa mở')}
 const late=now>deadline;if(late&&!ctx.allowLate){await cleanupFiles(files);return fail(409,'Đã quá hạn nộp')}
 const existing=await repo.findByRequirementGroup(ctx.requirementId,ctx.groupId),attempts=existing?.latestAttemptNumber||0;if(existing&&['COMPLETED','NOT_MET','GRADED'].includes(existing.status)){await cleanupFiles(files);return fail(409,'Bài nộp đã ở trạng thái kết thúc')}if(attempts&&!ctx.allowResubmission){await cleanupFiles(files);return fail(409,'Đợt nộp không cho phép nộp lại')}if(attempts>=ctx.maxAttempts){await cleanupFiles(files);return fail(409,'Đã đạt số lần nộp tối đa')}
 const max=(ctx.maxFileSizeMb||20)*1024*1024;if(files.some(f=>f.size>max)){await cleanupFiles(files);return fail(413,`Mỗi file không được vượt quá ${ctx.maxFileSizeMb||20} MB`)}
 if(ctx.requirementType==='WEEKLY_PROGRESS'){
  let raw;try{raw=JSON.parse(String(body.responses||'[]'))}catch{await cleanupFiles(files);return fail(400,'Dữ liệu nội dung tiến độ không hợp lệ')}
  if(!Array.isArray(raw)){await cleanupFiles(files);return fail(400,'Dữ liệu nội dung tiến độ không hợp lệ')}
  const configured=new Map(ctx.requiredItems.map(x=>[x.id,x])),received=new Set(),seen=new Set(),responseData=[];const urlTypes=new Set(['GITHUB_REPOSITORY','GITHUB_PULL_REQUEST','JIRA_BOARD','FIGMA','DEMO_VIDEO','OTHER_URL']);
  for(const value of raw){const item=configured.get(Number(value.itemId));if(!item||received.has(item.id)){await cleanupFiles(files);return fail(400,'Nội dung gửi lên không thuộc yêu cầu hoặc bị trùng')}received.add(item.id);if(item.type==='REPORT_FILE'){await cleanupFiles(files);return fail(400,'File báo cáo phải được tải lên đúng mục yêu cầu')}const textValue=String(value.value||'').trim();if(!textValue)continue;seen.add(item.id);if(urlTypes.has(item.type)){const valid=url(textValue);if(!valid){await cleanupFiles(files);return fail(400,`${item.name}: URL phải dùng HTTP hoặc HTTPS`)}responseData.push({itemId:item.id,urlValue:valid})}else responseData.push({itemId:item.id,textValue})}
  const fileData=[];for(const file of files){const match=/^item_(\d+)$/.exec(file.fieldname),item=match&&configured.get(Number(match[1]));if(!item||item.type!=='REPORT_FILE'||received.has(item.id)){await cleanupFiles(files);return fail(400,'File không thuộc mục báo cáo được yêu cầu')}received.add(item.id);seen.add(item.id);const fieldKey=file.fieldname;fileData.push({fieldKey,type:'REPORT_FILE',originalName:file.originalname,storedName:file.filename,relativePath:relativeUploadPath(file.filename),mimeType:file.mimetype,size:file.size});responseData.push({itemId:item.id,fileKey:fieldKey})}
  if(ctx.requiredItems.some(item=>item.isRequired&&!seen.has(item.id))){await cleanupFiles(files);return fail(400,'Vui lòng nhập đầy đủ các mục bắt buộc')}
  try{const saved=await repo.createAttempt(ctx,user.id,fileData,[],responseData,late);await notifyUsers([ctx.lecturerId],{type:'SUBMISSION_RECEIVED',title:'Có tiến độ tuần mới',message:'Nhóm '+ctx.groupName+' đã nộp tiến độ tuần '+ctx.weekNumber+'.',relatedEntityType:'SUBMISSION',relatedEntityId:saved.id,eventKey:'SUBMISSION_ATTEMPT:'+saved.id+':'+saved.latestAttemptNumber});return ok({...saved,attempts:await repo.attempts(saved.id)},late?'Nộp tiến độ trễ thành công':'Nộp tiến độ thành công',201)}catch(e){await cleanupFiles(files);throw e}
 }
 const fileTypes=files.map(f=>f.fieldname),github=url(body.githubUrl),video=url(body.videoUrl);if(body.githubUrl&&!github||body.videoUrl&&!video){await cleanupFiles(files);return fail(400,'GitHub hoặc video URL không hợp lệ')}const requiredTypes=ctx.requiredItems.map(x=>x.type),supplied=new Set([...fileTypes,...(github?['GITHUB_LINK']:[]),...(video?['VIDEO_LINK']:[])]);if([...supplied].some(t=>!requiredTypes.includes(t))||requiredTypes.some(t=>!supplied.has(t))){await cleanupFiles(files);return fail(400,'Phải nộp đúng và đủ các loại nội dung được yêu cầu')}const metadata=files.map(f=>({type:f.fieldname,originalName:f.originalname,storedName:f.filename,relativePath:relativeUploadPath(f.filename),mimeType:f.mimetype,size:f.size})),links=[...(github?[{type:'GITHUB_LINK',url:github}]:[]),...(video?[{type:'VIDEO_LINK',url:video}]:[])];try{const saved=await repo.createAttempt(ctx,user.id,metadata,links,[],late);return ok({...saved,attempts:await repo.attempts(saved.id)},'Nộp bài thành công',201)}catch(e){await cleanupFiles(files);throw e}
}export async function detail(id,user){const a=await access(id,user);return a.error||ok({...a.submission,attempts:await repo.attempts(a.submission.id)},'Lấy chi tiết bài nộp thành công')}
export async function getHistory(id,user){const a=await access(id,user);return a.error||ok(await repo.history(a.submission.id),'Lấy lịch sử nộp thành công')}
export async function attempt(id,attemptId,user){const a=await access(id,user);if(a.error)return a.error;const item=(await repo.attempts(a.submission.id)).find(x=>x.id===idOf(attemptId));return item?ok(item,'Lấy lần nộp thành công'):fail(404,'Không tìm thấy lần nộp')}
export async function lecturerList(requirementId,user){return ok(await repo.lecturerRequirementSubmissions(idOf(requirementId),user.id),'Lấy danh sách bài nộp thành công')}
export async function download(fileId,user){const f=await repo.findFile(idOf(fileId));if(!f)return{error:fail(404,'Không tìm thấy file')};const allowed=user.role==='LECTURER'?f.lecturerId===user.id:await repo.isGroupMember(f.groupId,user.id);if(!allowed)return{error:fail(403,'Bạn không có quyền tải file này')};let fullPath;try{fullPath=resolveStoredFile(f.relativePath);await fileAccess(fullPath)}catch(error){if(error?.code==='ENOENT'){console.warn(`Submission file missing: fileId=${f.id}, submissionId=${f.submissionId}`);return{error:fail(410,'Tệp đính kèm không còn tồn tại trên hệ thống.')}}return{error:fail(400,'Đường dẫn file không hợp lệ')}}return{file:f,fullPath}}
