import { useEffect,useState } from 'react'
import { BookOpen,Plus,Search,UserRoundCheck,Users } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { getUsers } from '../../api/adminApi'
import { createAcademic,listAcademic,setAcademicStatus,updateAcademic } from '../../api/academicsApi'
const configs={
 'academic-years':{fields:[['name','Tên năm học','text'],['startDate','Ngày bắt đầu','date'],['endDate','Ngày kết thúc','date']],columns:[['name','Tên năm học'],['startDate','Bắt đầu'],['endDate','Kết thúc']]},
 semesters:{fields:[['academicYearId','Năm học','academic-years'],['name','Tên học kỳ','text'],['code','Mã học kỳ','text'],['startDate','Ngày bắt đầu','date'],['endDate','Ngày kết thúc','date']],columns:[['code','Mã'],['name','Tên học kỳ'],['academicYearId','Năm học'],['startDate','Bắt đầu'],['endDate','Kết thúc']]},
 subjects:{fields:[['code','Mã môn học','text'],['name','Tên môn học','text'],['credits','Số tín chỉ','number'],['description','Mô tả','text']],columns:[['code','Mã môn'],['name','Tên môn học'],['credits','Tín chỉ']]},
 'course-classes':{fields:[['code','Mã lớp học phần','text'],['subjectId','Môn học','subjects'],['semesterId','Học kỳ','semesters'],['lecturerId','Giảng viên phụ trách','lecturers'],['maxStudents','Sĩ số tối đa','number'],['status','Trạng thái','status']],columns:[['code','Mã lớp'],['subjectId','Môn học'],['semesterId','Học kỳ'],['lecturerName','Giảng viên phụ trách'],['status','Trạng thái']]}
}
const initial={status:'ACTIVE'},date=v=>v?new Date(v).toLocaleDateString('vi-VN'):'—',statusText={ACTIVE:'Hoạt động',INACTIVE:'Đã khóa',COMPLETED:'Đã kết thúc',CANCELLED:'Đã hủy'}
export default function AcademicSummaryPage({resource,title}){const navigate=useNavigate(),key=resource==='academicYears'?'academic-years':resource==='courseClasses'?'course-classes':resource,config=configs[key],[items,setItems]=useState([]),[refs,setRefs]=useState({}),[form,setForm]=useState(initial),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1),[pages,setPages]=useState(1),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(null)
 const load=async()=>{try{setLoading(true);const r=await listAcademic(key,{page,pageSize:10,search});setItems(r.data.items||[]);setPages(r.data.totalPages||1)}catch(e){setMessage({type:'error',text:e.message})}finally{setLoading(false)}};useEffect(()=>{load()},[key,page]);useEffect(()=>{const types=[...new Set(config.fields.map(x=>x[2]).filter(x=>configs[x]))],jobs=types.map(x=>listAcademic(x,{pageSize:100}).then(r=>[x,r.data.items||[]]));if(config.fields.some(x=>x[2]==='lecturers'))jobs.push(getUsers({role:'LECTURER',status:'ACTIVE',pageSize:100,sortBy:'fullName',sortOrder:'asc'}).then(r=>['lecturers',r.data.items||[]]));Promise.all(jobs).then(x=>setRefs(Object.fromEntries(x))).catch(e=>setMessage({type:'error',text:e.message}))},[key])
 const display=(item,field)=>field.endsWith('Date')?date(item[field]):field==='academicYearId'?item.academicYearName||item[field]:field==='subjectId'?item.subjectName||item[field]:field==='semesterId'?item.semesterName||item[field]:field==='status'?statusText[item[field]]||item[field]:item[field]??'—'
 const edit=item=>{const next={};config.fields.forEach(([field])=>next[field]=field.endsWith('Date')&&item[field]?String(item[field]).slice(0,10):(item[field]??''));setForm(next);setEditing(item);setOpen(true)}
 const submit=async e=>{e.preventDefault();if(key==='course-classes'&&editing&&String(editing.lecturerId||'')!==String(form.lecturerId||'')&&!window.confirm('Xác nhận thay đổi giảng viên phụ trách lớp học phần?'))return;try{setSaving(true);editing?await updateAcademic(key,editing.id,form):await createAcademic(key,form);setMessage({type:'success',text:editing?'Cập nhật thành công.':'Thêm mới thành công.'});setOpen(false);setEditing(null);setForm(initial);load()}catch(x){setMessage({type:'error',text:x.message})}finally{setSaving(false)}}
 return <div className="admin-page"><div className="page-title admin-page-heading"><div><span className="eyebrow">QUẢN LÝ HỌC VỤ</span><h2>{title}</h2><p>Quản lý thông tin {title.toLowerCase()} trong hệ thống.</p></div><div className="toolbar-actions">{key==='course-classes'&&<><button className="btn-light" onClick={()=>navigate('/admin/students/import')}><Users size={17}/>Danh sách sinh viên</button><button className="btn-light" onClick={()=>navigate('/admin/course-classes')}><UserRoundCheck size={17}/>Phân công giảng viên</button></>}<button className="btn-primary" onClick={()=>{setEditing(null);setForm(initial);setOpen(true)}}><Plus size={18}/>Thêm mới</button></div></div>{message&&<div className={`alert ${message.type}`}>{message.text}</div>}<div className="panel"><form className="admin-filterbar compact" onSubmit={e=>{e.preventDefault();page===1?load():setPage(1)}}><label className="search-field"><Search size={18}/><input placeholder={`Tìm kiếm ${title.toLowerCase()}...`} value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn-primary">Tìm kiếm</button></form>{loading?<div className="skeleton-list">{[1,2,3].map(x=><div key={x}/>)}</div>:!items.length?<div className="empty-state"><BookOpen size={42}/><h3>Chưa có dữ liệu</h3><p>Nhấn “Thêm mới” để bắt đầu.</p></div>:<div className="table-wrap"><table><thead><tr>{config.columns.map(x=><th key={x[0]}>{x[1]}</th>)}<th>Trạng thái sử dụng</th><th>Thao tác</th></tr></thead><tbody>{items.map(item=><tr key={item.id}>{config.columns.map(x=><td key={x[0]}>{display(item,x[0])}</td>)}<td><span className={`status-pill ${item.isActive?'active':'inactive'}`}>{item.isActive?'Hoạt động':'Đã khóa'}</span></td><td><div className="compact-actions"><button onClick={()=>edit(item)}>Sửa</button><button onClick={async()=>{if(window.confirm(`${item.isActive?'Khóa':'Mở khóa'} dữ liệu này?`)){await setAcademicStatus(key,item.id,!item.isActive);load()}}}>{item.isActive?'Khóa':'Mở khóa'}</button></div></td></tr>)}</tbody></table></div>}<div className="pagination-bar"><button disabled={page<=1} onClick={()=>setPage(page-1)}>Trước</button><span>Trang {page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)}>Sau</button></div></div>
 {open&&<div className="modal-overlay"><div className="modal-card admin-modal"><div className="modal-header"><div><span className="eyebrow">{editing?'CẬP NHẬT':'THÊM MỚI'}</span><h3>{title}</h3></div><button onClick={()=>setOpen(false)}>×</button></div><form onSubmit={submit}><div className="form-grid">{config.fields.map(([field,label,type])=><label key={field}>{label}{configs[type]?<select required value={form[field]||''} onChange={e=>setForm({...form,[field]:e.target.value})}><option value="">-- Chọn --</option>{(refs[type]||[]).map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} — `:''}{x.name}</option>)}</select>:type==='lecturers'?<select value={form[field]||''} onChange={e=>setForm({...form,[field]:e.target.value})}><option value="">Chưa phân công</option>{(refs.lecturers||[]).map(x=><option key={x.id} value={x.id}>{x.userCode} — {x.fullName} — {x.email}</option>)}</select>:type==='status'?<select value={form[field]||'ACTIVE'} onChange={e=>setForm({...form,[field]:e.target.value})}>{Object.entries(statusText).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input required={!['description','maxStudents'].includes(field)} type={type} value={form[field]||''} onChange={e=>setForm({...form,[field]:e.target.value})}/>}</label>)}</div><div className="modal-actions"><button type="button" className="btn-light" onClick={()=>setOpen(false)}>Hủy</button><button className="btn-primary" disabled={saving}>{saving?'Đang lưu...':'Lưu thay đổi'}</button></div></form></div></div>}</div>}
