import { useEffect,useState } from 'react'
import { getUsers } from '../../api/adminApi'
import { bulkEnrollStudents,confirmStudentCsv,downloadStudentImportTemplate,exportCourseClassStudents,listAcademic,listCourseClassStudents,previewStudentCsv } from '../../api/academicsApi'

function saveBlob(blob,name){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
function csvCell(value){let text=String(value??'');if(/^[=+\-@\t\r]/.test(text))text=`'${text}`;return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
function errorCsv(rows){const data=[['rowNumber','studentCode','fullName','email','errors'],...rows.filter(row=>!row.valid).map(row=>[row.rowNumber,row.studentCode,row.fullName,row.email,row.errors.join(' | ')])];return new Blob(['\uFEFF'+data.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})}

export default function BulkStudentImportPage(){
 const[classes,setClasses]=useState([]),[courseClassId,setCourseClassId]=useState(''),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[result,setResult]=useState(null),[students,setStudents]=useState([]),[selected,setSelected]=useState([]),[enrolled,setEnrolled]=useState([]),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const loadClasses=()=>listAcademic('course-classes',{pageSize:100}).then(response=>setClasses(response.data.items||[])).catch(err=>setError(err.message))
 const loadStudents=()=>getUsers({role:'STUDENT',status:'ACTIVE',search,pageSize:100,sortBy:'fullName',sortOrder:'asc'}).then(response=>setStudents(response.data.items||[])).catch(err=>setError(err.message))
 const loadEnrolled=()=>courseClassId?listCourseClassStudents(courseClassId,{pageSize:100}).then(response=>setEnrolled(response.data.items||[])).catch(err=>setError(err.message)):setEnrolled([])
 useEffect(()=>{loadClasses();loadStudents()},[])
 useEffect(()=>{setPreview(null);setResult(null);setSelected([]);loadEnrolled()},[courseClassId])
 const previewFile=async event=>{event.preventDefault();if(!courseClassId||!file)return setError('Vui lòng chọn lớp học phần và file CSV.');setBusy(true);setError('');setResult(null);try{setPreview((await previewStudentCsv(courseClassId,file)).data)}catch(err){setError(err.message)}finally{setBusy(false)}}
 const confirm=async()=>{setBusy(true);setError('');try{const response=await confirmStudentCsv(preview.previewId,Number(courseClassId));setResult(response.data);setPreview(null);setFile(null);await Promise.all([loadStudents(),loadEnrolled()])}catch(err){setError(err.message)}finally{setBusy(false)}}
 const bulk=async()=>{if(!selected.length)return setError('Chọn ít nhất một sinh viên.');setBusy(true);setError('');try{const response=await bulkEnrollStudents(courseClassId,selected);setResult(response.data);setSelected([]);await loadEnrolled()}catch(err){setError(err.message)}finally{setBusy(false)}}
 const downloadTemplate=async()=>{try{saveBlob(await downloadStudentImportTemplate(),'student-import-template.csv')}catch(err){setError(err.message)}}
 const exportStudents=async()=>{try{saveBlob(await exportCourseClassStudents(courseClassId),`course-class-${courseClassId}-students.csv`)}catch(err){setError(err.message)}}
 const enrolledIds=new Set(enrolled.map(item=>item.id))
 return <div>
  <div className="page-title"><h2>Nhập danh sách sinh viên</h2><p>Tạo tài khoản sinh viên từ CSV UTF-8 và xếp vào lớp học phần.</p></div>
  {error&&<div className="alert error">{error}</div>}{result&&<div className="alert success">Hoàn tất: {result.createdCount??result.enrolledCount??0} sinh viên mới, {result.skippedCount??0} đã tồn tại.</div>}
  <div className="panel"><h3>1. Chọn lớp học phần</h3><select value={courseClassId} onChange={event=>setCourseClassId(event.target.value)}><option value="">-- Chọn lớp học phần --</option>{classes.filter(item=>item.isActive&&item.status==='ACTIVE').map(item=><option key={item.id} value={item.id}>{item.code} — {item.subjectName}</option>)}</select></div>
  <form className="panel" onSubmit={previewFile}><div className="row-between"><div><h3>2. Tải lên và xem trước CSV</h3><p>Cột bắt buộc: studentCode,fullName,email,password. Tối đa 500 dòng và 2 MB.</p></div><button type="button" className="btn-light" onClick={downloadTemplate}>Tải file mẫu</button></div><input type="file" accept=".csv,text/csv" onChange={event=>{setFile(event.target.files?.[0]||null);setPreview(null)}}/><button className="btn-primary" disabled={busy||!courseClassId||!file}>{busy?'Đang kiểm tra...':'Xem trước dữ liệu'}</button></form>
  {preview&&<div className="panel"><div className="row-between"><h3>3. Kết quả kiểm tra</h3><span>Hợp lệ: {preview.validCount} · Lỗi: {preview.invalidCount}</span></div><div className="table-wrap"><table><thead><tr><th>Dòng</th><th>MSSV</th><th>Họ tên</th><th>Email</th><th>Kết quả</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.studentCode}</td><td>{row.fullName}</td><td>{row.email}</td><td>{row.valid?'Hợp lệ':row.errors.join(' ')}</td></tr>)}</tbody></table></div><div className="row-actions">{preview.invalidCount>0&&<button className="btn-light" onClick={()=>saveBlob(errorCsv(preview.rows),'loi-import-sinh-vien.csv')}>Tải CSV lỗi</button>}<button className="btn-primary" disabled={busy||preview.invalidCount>0||preview.validCount===0} onClick={confirm}>Xác nhận nhập toàn bộ</button></div>{preview.invalidCount>0&&<p className="alert error">Hãy sửa tất cả dòng lỗi và xem trước lại trước khi nhập.</p>}</div>}
  <div className="panel"><div className="row-between"><div><h3>4. Thêm tài khoản đã có</h3><p>Chọn nhiều sinh viên để xếp vào lớp đã chọn.</p></div><button className="btn-light" disabled={!courseClassId} onClick={exportStudents}>Xuất sinh viên trong lớp</button></div><form className="student-search-row" onSubmit={event=>{event.preventDefault();loadStudents()}}><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Tìm MSSV, họ tên hoặc email"/><button className="btn-light">Tìm</button></form><div className="table-wrap"><table><thead><tr><th>Chọn</th><th>MSSV</th><th>Họ tên</th><th>Email</th><th>Trạng thái</th></tr></thead><tbody>{students.map(student=><tr key={student.id}><td><input type="checkbox" disabled={!courseClassId||enrolledIds.has(student.id)} checked={selected.includes(student.id)} onChange={event=>setSelected(event.target.checked?[...selected,student.id]:selected.filter(id=>id!==student.id))}/></td><td>{student.userCode}</td><td>{student.fullName}</td><td>{student.email}</td><td>{enrolledIds.has(student.id)?'Đã trong lớp':'Chưa xếp vào lớp'}</td></tr>)}</tbody></table></div><button className="btn-primary" disabled={busy||!courseClassId||!selected.length} onClick={bulk}>Thêm {selected.length} sinh viên vào lớp</button></div>
  {courseClassId&&<div className="panel"><h3>Sinh viên hiện có trong lớp ({enrolled.length})</h3>{enrolled.map(item=><p key={item.id}>{item.studentCode} — {item.fullName} — {item.email}</p>)}</div>}
 </div>
}
