import { useEffect, useState } from 'react'
import { Select } from 'antd'
import { CheckCircle2, Download, FileSpreadsheet, Upload, Users, XCircle } from 'lucide-react'
import { confirmLecturers, downloadLecturerTemplate, exportLecturers, previewLecturers } from '../../api/lecturerImportApi'
import { listOrganization } from '../../api/organizationApi'

const save=(blob,name)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
const cell=value=>{let text=String(value??'');if(/^[=+\-@\t\r]/.test(text))text=`'${text}`;return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
const errorFile=rows=>new Blob(['\uFEFF'+[['rowNumber','lecturerCode','fullName','email','academicDegree','errors'],...rows.filter(x=>!x.valid).map(x=>[x.rowNumber,x.lecturerCode,x.fullName,x.email,x.academicDegree,x.errors.join(' | ')])].map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})

export default function BulkLecturerImportPage(){
  const[file,setFile]=useState(null),[preview,setPreview]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[faculties,setFaculties]=useState([]),[facultyId,setFacultyId]=useState('')
  useEffect(()=>{listOrganization('faculties',{pageSize:100,isActive:true}).then(r=>setFaculties(r.data.items||[])).catch(()=>setFaculties([]))},[])
  const inspect=async e=>{e.preventDefault();if(!file)return;try{setBusy(true);setError('');setPreview((await previewLecturers(file)).data)}catch(x){setError(x.message)}finally{setBusy(false)}}
  const confirm=async()=>{try{setBusy(true);const r=await confirmLecturers(preview.previewId);setResult(r.data);setPreview(null);setFile(null)}catch(x){setError(x.message)}finally{setBusy(false)}}
  const faculty=faculties.find(item=>Number(item.id)===Number(facultyId))
  return <div className="admin-page">
    <div className="page-title admin-page-heading"><div><span className="eyebrow">QUẢN LÝ NGƯỜI DÙNG</span><h2>Nhập danh sách giảng viên</h2><p>Tạo hàng loạt tài khoản giảng viên từ file CSV UTF-8.</p></div><div className="toolbar-actions"><Select showSearch allowClear optionFilterProp="label" placeholder="Tất cả khoa" value={facultyId||undefined} options={faculties.map(item=>({value:item.id,label:`${item.facultyCode} — ${item.facultyName}`}))} onChange={value=>setFacultyId(value||'')}/><button className="btn-light" onClick={async()=>save(await exportLecturers(facultyId),`danh-sach-giang-vien-${faculty?.facultyCode||'tat-ca'}.csv`)}><Download size={17}/>Xuất danh sách</button><button className="btn-primary" onClick={async()=>save(await downloadLecturerTemplate(),'mau-import-giang-vien.csv')}><FileSpreadsheet size={17}/>Tải file mẫu</button></div></div>
    {error&&<div className="alert error">{error}</div>}{result&&<div className="alert success">Đã tạo thành công {result.createdCount} tài khoản giảng viên.</div>}
    <form className="panel import-dropzone" onSubmit={inspect}><Upload size={36}/><h3>Chọn file CSV giảng viên</h3><p>Cột academicDegree là tùy chọn; file 4 cột cũ vẫn import được. Tối đa 2 MB và 500 dòng.</p><input type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null)}}/><button className="btn-primary" disabled={!file||busy}>{busy?'Đang kiểm tra...':'Xem trước dữ liệu'}</button></form>
    {preview&&<div className="panel"><div className="preview-summary"><div className="summary-valid"><CheckCircle2/><span><strong>{preview.validCount}</strong>Dòng hợp lệ</span></div><div className="summary-invalid"><XCircle/><span><strong>{preview.invalidCount}</strong>Dòng lỗi</span></div><div><Users/><span><strong>{preview.totalRows}</strong>Tổng số dòng</span></div></div><div className="table-wrap"><table><thead><tr><th>Dòng</th><th>Mã giảng viên</th><th>Họ và tên</th><th>Email</th><th>Học vị</th><th>Kết quả</th></tr></thead><tbody>{preview.rows.map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.lecturerCode}</td><td>{row.fullName}</td><td>{row.email}</td><td>{row.academicDegree||'—'}</td><td><span className={`import-result ${row.valid?'valid':'invalid'}`}>{row.valid?'Hợp lệ':row.errors.join(' ')}</span></td></tr>)}</tbody></table></div><div className="modal-actions">{preview.invalidCount>0&&<button className="btn-light" onClick={()=>save(errorFile(preview.rows),'loi-import-giang-vien.csv')}>Tải CSV lỗi</button>}<button className="btn-primary" disabled={busy||preview.invalidCount>0||!preview.validCount} onClick={confirm}>Xác nhận nhập toàn bộ</button></div></div>}
  </div>
}
