/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect,useMemo,useRef,useState } from 'react'
import { Check,CheckCircle2,Download,FileSpreadsheet,Search,Trash2,UploadCloud,Users,XCircle } from 'lucide-react'
import { getUsers } from '../../api/adminApi'
import { bulkEnrollStudents,confirmStudentCsv,downloadStudentImportTemplate,exportCourseClassStudents,listAcademic,listCourseClassStudents,previewStudentCsv } from '../../api/academicsApi'

const saveBlob=(blob,name)=>{const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}
const csvCell=value=>{let text=String(value??'');if(/^[=+\-@\t\r]/.test(text))text=`'${text}`;return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text}
const errorCsv=rows=>new Blob(['\uFEFF'+[['rowNumber','studentCode','fullName','email','errors'],...rows.filter(row=>!row.valid).map(row=>[row.rowNumber,row.studentCode,row.fullName,row.email,(row.errors||[]).join(' | ')])].map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})
const formatSize=size=>size<1024?`${size} B`:size<1024*1024?`${(size/1024).toFixed(1)} KB`:`${(size/1024/1024).toFixed(2)} MB`
const steps=['Chọn lớp học phần','Tải file CSV','Xem trước và kiểm tra dữ liệu','Xác nhận nhập danh sách']

export default function BulkStudentImportPage(){
 const fileInput=useRef(null)
 const[tab,setTab]=useState('csv'),[classes,setClasses]=useState([]),[courseClassId,setCourseClassId]=useState(''),[file,setFile]=useState(null),[fileError,setFileError]=useState(''),[preview,setPreview]=useState(null),[csvStep,setCsvStep]=useState(1),[csvResult,setCsvResult]=useState(null),[previewFilter,setPreviewFilter]=useState('all')
 const[students,setStudents]=useState([]),[selected,setSelected]=useState([]),[enrolled,setEnrolled]=useState([]),[search,setSearch]=useState(''),[enrollResult,setEnrollResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const activeClasses=useMemo(()=>classes.filter(item=>item.isActive&&item.status==='ACTIVE'),[classes]),selectedClass=activeClasses.find(item=>String(item.id)===String(courseClassId)),enrolledIds=new Set(enrolled.map(item=>item.id))
 const duplicateRows=preview?.rows?.filter(row=>(row.errors||[]).some(value=>/trùng|tồn tại/i.test(value)))||[]
 const visibleRows=(preview?.rows||[]).filter(row=>previewFilter==='all'||(previewFilter==='valid'?row.valid:!row.valid))
 const loadClasses=()=>listAcademic('course-classes',{pageSize:100}).then(response=>setClasses(response.data.items||[])).catch(err=>setError(err.message))
 const loadStudents=()=>getUsers({role:'STUDENT',status:'ACTIVE',search,pageSize:100,sortBy:'fullName',sortOrder:'asc'}).then(response=>setStudents(response.data.items||[])).catch(err=>setError(err.message))
 const loadEnrolled=()=>courseClassId?listCourseClassStudents(courseClassId,{pageSize:100}).then(response=>setEnrolled(response.data.items||[])).catch(err=>setError(err.message)):setEnrolled([])
 useEffect(()=>{loadClasses();loadStudents()},[])
 useEffect(()=>{setPreview(null);setCsvResult(null);setEnrollResult(null);setSelected([]);setCsvStep(courseClassId?2:1);loadEnrolled()},[courseClassId])
 const chooseFile=next=>{setPreview(null);setCsvResult(null);setFileError('');if(!next){setFile(null);setCsvStep(courseClassId?2:1);return}if(!/\.csv$/i.test(next.name)){setFile(null);setFileError('Vui lòng chọn đúng file CSV.');return}if(next.size>2*1024*1024){setFile(null);setFileError('File CSV không được vượt quá 2 MB.');return}setFile(next);setCsvStep(courseClassId?2:1)}
 const previewFile=async()=>{if(!courseClassId||!file)return setError('Vui lòng chọn lớp học phần và file CSV.');setBusy(true);setError('');try{setPreview((await previewStudentCsv(courseClassId,file)).data);setCsvStep(3)}catch(err){setError(err.message)}finally{setBusy(false)}}
 const confirm=async()=>{setBusy(true);setError('');try{const response=await confirmStudentCsv(preview.previewId,Number(courseClassId));setCsvResult(response.data);await Promise.all([loadStudents(),loadEnrolled()])}catch(err){setError(err.message)}finally{setBusy(false)}}
 const bulk=async()=>{if(!courseClassId)return setError('Vui lòng chọn lớp học phần.');if(!selected.length)return setError('Vui lòng chọn ít nhất một sinh viên.');setBusy(true);setError('');try{const response=await bulkEnrollStudents(courseClassId,selected);setEnrollResult(response.data);setSelected([]);await loadEnrolled()}catch(err){setError(err.message)}finally{setBusy(false)}}
 const downloadTemplate=async()=>{try{saveBlob(await downloadStudentImportTemplate(),'mau-nhap-sinh-vien.csv')}catch(err){setError(err.message)}}
 const exportStudents=async()=>{if(!courseClassId)return setError('Vui lòng chọn lớp học phần trước khi xuất danh sách.');try{saveBlob(await exportCourseClassStudents(courseClassId),`sinh-vien-lop-${courseClassId}.csv`)}catch(err){setError(err.message)}}
 const resetCsv=()=>{setFile(null);setPreview(null);setCsvResult(null);setFileError('');setCsvStep(courseClassId?2:1);if(fileInput.current)fileInput.current.value=''}
 return <div className="admin-page student-import-page">
  <div className="page-title admin-page-heading"><div><span className="eyebrow">QUẢN LÝ LỚP HỌC PHẦN</span><h2>Nhập danh sách sinh viên</h2><p>Tạo tài khoản sinh viên từ CSV hoặc thêm các tài khoản hiện có vào lớp học phần.</p></div><div className="toolbar-actions"><button className="btn-light" onClick={downloadTemplate}><FileSpreadsheet size={17}/>Tải file mẫu</button><button className="btn-light" disabled={!courseClassId} onClick={exportStudents}><Download size={17}/>Xuất danh sách lớp</button></div></div>
  {error&&<div className="alert error"><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
  <div className="import-tabs" role="tablist"><button role="tab" aria-selected={tab==='csv'} className={tab==='csv'?'active':''} onClick={()=>setTab('csv')}>Nhập sinh viên mới từ CSV</button><button role="tab" aria-selected={tab==='existing'} className={tab==='existing'?'active':''} onClick={()=>setTab('existing')}>Thêm sinh viên đã có</button></div>
  {tab==='csv'?<div className="import-workspace">
   <ol className="import-stepper">{steps.map((label,index)=>{const number=index+1,status=csvResult||csvStep>number?'done':csvStep===number?'current':'pending';return <li className={status} key={label}><span>{status==='done'?<Check/>:number}</span><strong>{label}</strong></li>})}</ol>
   {csvResult?<section className="panel import-success-state"><CheckCircle2/><h3>Nhập danh sách thành công</h3><p>Toàn bộ dữ liệu đã được xử lý theo transaction all-or-nothing.</p><div><strong>{csvResult.createdCount??0}<small>Tài khoản đã tạo</small></strong><strong>{csvResult.enrolledCount??csvResult.createdCount??0}<small>Sinh viên đã xếp lớp</small></strong></div><div className="row-actions"><button className="btn-light" onClick={()=>{setTab('existing');loadEnrolled()}}>Xem danh sách sinh viên</button><button className="btn-primary" onClick={resetCsv}>Nhập danh sách khác</button></div></section>:<>
    <section className="panel import-section"><span className="section-number">1</span><div className="import-section-heading"><h3>Chọn lớp học phần</h3><p>Chọn lớp sẽ nhận danh sách sinh viên từ file CSV.</p></div>{activeClasses.length?<label className="import-field">Lớp học phần<select value={courseClassId} onChange={event=>setCourseClassId(event.target.value)}><option value="">-- Chọn lớp học phần --</option>{activeClasses.map(item=><option key={item.id} value={item.id}>{item.code} — {item.subjectName} — {item.lecturerName||'Chưa phân công'}</option>)}</select></label>:<div className="empty-state small"><Users/><h3>Chưa có lớp học phần phù hợp</h3><p>Không tìm thấy lớp đang hoạt động.</p></div>}</section>
    <section className={`panel import-section ${!courseClassId?'disabled-section':''}`}><span className="section-number">2</span><div className="import-section-heading"><h3>Tải file CSV</h3><p>Chuẩn bị file đúng cấu trúc trước khi xem trước dữ liệu.</p></div><div className={`custom-upload ${fileError?'invalid':''}`} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();chooseFile(event.dataTransfer.files?.[0])}}><UploadCloud/><h4>Kéo thả file CSV vào đây hoặc</h4><button type="button" className="btn-primary" disabled={!courseClassId} onClick={()=>fileInput.current?.click()}>Chọn file từ máy tính</button><p>CSV UTF-8 · Tối đa 2 MB · Tối đa 500 dòng</p><input ref={fileInput} className="visually-hidden" type="file" accept=".csv,text/csv" onChange={event=>chooseFile(event.target.files?.[0]||null)}/></div>{file&&<div className="selected-file"><FileSpreadsheet/><span><strong>{file.name}</strong><small>{formatSize(file.size)} · File hợp lệ</small></span><button aria-label="Xóa file" onClick={()=>chooseFile(null)}><Trash2/></button></div>}{fileError&&<div className="field-error"><XCircle/>{fileError}</div>}<div className="import-actions"><button className="btn-primary" disabled={busy||!courseClassId||!file} onClick={previewFile}>{busy?<><span className="button-spinner"/>Đang xử lý...</>:<>Xem trước dữ liệu</>}</button></div></section>
    {preview&&csvStep===3&&<section className="panel import-section preview-section"><span className="section-number">3</span><div className="import-section-heading"><h3>Xem trước và kiểm tra dữ liệu</h3><p>Kiểm tra toàn bộ lỗi trước khi xác nhận nhập danh sách.</p></div><div className="preview-summary four"><div><Users/><span><strong>{preview.totalRows??preview.rows.length}</strong>Tổng số dòng</span></div><div className="summary-valid"><CheckCircle2/><span><strong>{preview.validCount}</strong>Dòng hợp lệ</span></div><div className="summary-invalid"><XCircle/><span><strong>{preview.invalidCount}</strong>Dòng có lỗi</span></div><div><FileSpreadsheet/><span><strong>{duplicateRows.length}</strong>Dòng bị trùng</span></div></div><div className="preview-filters"><button className={previewFilter==='all'?'active':''} onClick={()=>setPreviewFilter('all')}>Tất cả</button><button className={previewFilter==='valid'?'active':''} onClick={()=>setPreviewFilter('valid')}>Hợp lệ</button><button className={previewFilter==='invalid'?'active':''} onClick={()=>setPreviewFilter('invalid')}>Có lỗi</button></div><div className="table-wrap"><table className="preview-table"><thead><tr><th>STT</th><th>Mã sinh viên</th><th>Họ và tên</th><th>Email</th><th>Trạng thái</th><th>Chi tiết lỗi</th></tr></thead><tbody>{visibleRows.map(row=>{const duplicate=(row.errors||[]).some(value=>/trùng|tồn tại/i.test(value));return <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.studentCode}</td><td>{row.fullName}</td><td>{row.email}</td><td><span className={`import-badge ${row.valid?'valid':duplicate?'duplicate':'invalid'}`}>{row.valid?'Hợp lệ':duplicate?'Bị trùng':'Có lỗi'}</span></td><td>{row.valid?'—':(row.errors||[]).join(' · ')}</td></tr>})}</tbody></table></div>{preview.invalidCount>0&&<div className="import-warning"><XCircle/><span><strong>Chưa thể xác nhận nhập danh sách</strong>Hãy sửa tất cả dòng lỗi vì hệ thống xử lý theo chế độ all-or-nothing.</span><button className="btn-light" onClick={()=>saveBlob(errorCsv(preview.rows),'loi-import-sinh-vien.csv')}>Tải CSV lỗi</button></div>}<div className="import-actions"><button className="btn-light" onClick={()=>{setPreview(null);setCsvStep(2)}}>Quay lại</button><button className="btn-primary" disabled={preview.invalidCount>0||preview.validCount===0} onClick={()=>setCsvStep(4)}>Tiếp tục xác nhận</button></div></section>}
    {preview&&csvStep===4&&<section className="panel import-section confirm-section"><span className="section-number">4</span><div className="import-section-heading"><h3>Xác nhận nhập danh sách</h3><p>Kiểm tra lần cuối trước khi tạo tài khoản và xếp lớp.</p></div><div className="confirm-box"><div><span>Lớp được chọn</span><strong>{selectedClass?.code} — {selectedClass?.subjectName}</strong></div><div><span>Số tài khoản sẽ tạo</span><strong>{preview.validCount}</strong></div><div><span>Số sinh viên sẽ xếp vào lớp</span><strong>{preview.validCount}</strong></div><p>Toàn bộ dữ liệu được xử lý trong một transaction. Nếu một dòng thất bại, không có dữ liệu nào được ghi nhận.</p></div><div className="import-actions"><button className="btn-light" onClick={()=>setCsvStep(3)}>Quay lại</button><button className="btn-primary" disabled={busy} onClick={confirm}>{busy?<><span className="button-spinner"/>Đang xử lý...</>:'Xác nhận nhập danh sách'}</button></div></section>}
   </>}</div>:<div className="import-workspace"><section className="panel import-section"><div className="import-section-heading"><h3>1. Chọn lớp học phần</h3><p>Chọn lớp cần bổ sung các tài khoản sinh viên hiện có.</p></div><label className="import-field">Lớp học phần<select value={courseClassId} onChange={event=>setCourseClassId(event.target.value)}><option value="">-- Chọn lớp học phần --</option>{activeClasses.map(item=><option key={item.id} value={item.id}>{item.code} — {item.subjectName} — {item.lecturerName||'Chưa phân công'}</option>)}</select></label></section><section className="panel import-section"><div className="import-section-heading"><h3>2. Tìm và chọn sinh viên</h3><p>Chỉ hiển thị tài khoản sinh viên đang hoạt động.</p></div><form className="existing-search" onSubmit={event=>{event.preventDefault();loadStudents()}}><label><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Tìm theo MSSV, họ tên hoặc email"/></label><button className="btn-primary">Tìm kiếm</button></form><div className="selection-toolbar"><label><input type="checkbox" disabled={!courseClassId} checked={students.filter(item=>!enrolledIds.has(item.id)).length>0&&students.filter(item=>!enrolledIds.has(item.id)).every(item=>selected.includes(item.id))} onChange={event=>setSelected(event.target.checked?students.filter(item=>!enrolledIds.has(item.id)).map(item=>item.id):[])}/>Chọn tất cả trên trang</label><strong>Đã chọn {selected.length} sinh viên</strong></div><div className="table-wrap"><table><thead><tr><th>Chọn</th><th>MSSV</th><th>Họ và tên</th><th>Email</th><th>Trạng thái</th></tr></thead><tbody>{students.map(student=><tr key={student.id}><td><input type="checkbox" disabled={!courseClassId||enrolledIds.has(student.id)} checked={selected.includes(student.id)} onChange={event=>setSelected(event.target.checked?[...selected,student.id]:selected.filter(id=>id!==student.id))}/></td><td>{student.userCode}</td><td>{student.fullName}</td><td>{student.email}</td><td><span className={`status-pill ${enrolledIds.has(student.id)?'inactive':'active'}`}>{enrolledIds.has(student.id)?'Đã trong lớp':'Có thể thêm'}</span></td></tr>)}</tbody></table></div><div className="import-actions"><button className="btn-primary" disabled={busy||!courseClassId||!selected.length} onClick={bulk}>{busy?<><span className="button-spinner"/>Đang xử lý...</>:`Thêm ${selected.length} sinh viên vào lớp`}</button></div>{enrollResult&&<div className="enroll-result"><CheckCircle2/><span><strong>Đã hoàn tất thêm sinh viên</strong>Thành công: {enrollResult.enrolledCount??enrollResult.successCount??0} · Bỏ qua: {enrollResult.skippedCount??0}{enrollResult.skippedReason?` · ${enrollResult.skippedReason}`:''}</span></div>}</section>{courseClassId&&<section className="panel enrolled-summary"><h3>Sinh viên hiện có trong lớp</h3><strong>{enrolled.length}</strong><span>tài khoản đang được xếp lớp</span></section>}</div>}
 </div>
}
