import { useEffect, useState } from 'react'
import { getUsers } from '../../api/adminApi'
import { listAcademic, listCourseClassLecturers, replaceCourseClassLecturers } from '../../api/academicsApi'
import LecturerAssignmentFields from '../../components/LecturerAssignmentFields'

export default function LecturerAssignmentsPage(){
  const [classes,setClasses]=useState([]),[lecturers,setLecturers]=useState([]),[classId,setClassId]=useState('')
  const [primaryId,setPrimaryId]=useState(''),[coIds,setCoIds]=useState([]),[assignments,setAssignments]=useState([])
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
  useEffect(()=>{Promise.all([listAcademic('course-classes',{pageSize:100}),getUsers({role:'LECTURER',status:'ACTIVE',pageSize:100,sortBy:'fullName',sortOrder:'asc'})]).then(([c,l])=>{setClasses(c.data?.items||[]);setLecturers(l.data?.items||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
  useEffect(()=>{if(!classId)return;listCourseClassLecturers(classId).then(r=>{const list=r.data||[];setAssignments(list);setPrimaryId(list.find(x=>x.assignmentRole==='PRIMARY'&&x.isActive)?.lecturerId||'');setCoIds(list.filter(x=>x.assignmentRole==='CO_LECTURER'&&x.isActive).map(x=>x.lecturerId));setError('')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[classId])
  const save=async()=>{try{setSaving(true);setError('');const payload=[...(primaryId?[{lecturerId:Number(primaryId),assignmentRole:'PRIMARY'}]:[]),...coIds.map(lecturerId=>({lecturerId:Number(lecturerId),assignmentRole:'CO_LECTURER'}))];const r=await replaceCourseClassLecturers(classId,payload);setAssignments(r.data||[]);setMessage('Đã cập nhật phân công giảng viên.')}catch(e){setError(e.message)}finally{setSaving(false)}}
  return <div className="admin-page"><div className="page-title"><span className="eyebrow">QUẢN LÝ HỌC VỤ</span><h2>Phân công giảng viên</h2><p>Một giảng viên có thể giảng dạy nhiều lớp trong cùng học kỳ.</p></div>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<div className="panel"><label>Chọn lớp học phần<select value={classId} onChange={e=>{setClassId(e.target.value);if(!e.target.value){setAssignments([]);setPrimaryId('');setCoIds([])}}}><option value="">-- Chọn lớp --</option>{classes.map(x=><option key={x.id} value={x.id}>{x.code} — {x.subjectName} — {x.semesterName}</option>)}</select></label>{classId&&<><LecturerAssignmentFields lecturers={lecturers} primaryId={primaryId} coLecturerIds={coIds} disabled={loading||saving} onPrimaryChange={value=>{setPrimaryId(value);setCoIds(ids=>ids.filter(id=>String(id)!==String(value)))}} onCoLecturersChange={setCoIds}/><div className="assignment-load-info">{assignments.map(x=><p key={x.lecturerId}>{x.code} — {x.fullName}: đang giảng dạy {x.semesterClassCount||0} lớp trong học kỳ hiện tại.</p>)}</div><button className="btn-primary" disabled={saving||loading} onClick={save}>{saving?'Đang lưu...':'Lưu phân công'}</button></>}</div></div>
}
