import { useCallback,useEffect,useState } from 'react'
import { Building2,GraduationCap,Plus,Search,Trash2,Users } from 'lucide-react'
import { getUsers } from '../../api/adminApi'
import * as api from '../../api/organizationApi'
import ConfirmModal from '../../components/common/ConfirmModal'
import DataTable from '../../components/common/DataTable'
import FormField from '../../components/common/FormField'
import Modal from '../../components/common/Modal'
import PageHeader from '../../components/common/PageHeader'
import { ErrorState } from '../../components/common/UiState'

const definitions={faculties:{resource:'faculties',title:'Khoa',Icon:Building2,empty:{facultyCode:'',facultyName:'',description:''}},classes:{resource:'administrative-classes',title:'Lớp hành chính',Icon:GraduationCap,empty:{classCode:'',className:'',facultyId:'',admissionYear:'',academicProgram:'',advisorLecturerId:'',description:''}}}
const formatDate=value=>value?new Date(value).toLocaleDateString('vi-VN'):'—'

export default function OrganizationManagementPage({type}){
 const config=definitions[type],isClass=type==='classes'
 const[items,setItems]=useState([]),[page,setPage]=useState(1),[pages,setPages]=useState(1),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[facultyFilter,setFacultyFilter]=useState(''),[yearFilter,setYearFilter]=useState('')
 const[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[message,setMessage]=useState(null),[faculties,setFaculties]=useState([]),[lecturers,setLecturers]=useState([]),[allStudents,setAllStudents]=useState([])
 const[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(config.empty),[errors,setErrors]=useState({}),[saving,setSaving]=useState(false),[confirm,setConfirm]=useState(null)
 const[classForStudents,setClassForStudents]=useState(null),[students,setStudents]=useState([]),[studentId,setStudentId]=useState(''),[studentBusy,setStudentBusy]=useState(false)
 const load=useCallback(async()=>{try{setLoading(true);setLoadError('');const r=await api.listOrganization(config.resource,{page,pageSize:10,search,isActive:status,facultyId:facultyFilter,admissionYear:yearFilter});setItems(r.data.items||[]);setPages(r.data.totalPages||1)}catch(e){setLoadError(e.message)}finally{setLoading(false)}},[config.resource,page,search,status,facultyFilter,yearFilter])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(!isClass)return;Promise.all([api.listOrganization('faculties',{pageSize:100,isActive:true}),getUsers({role:'LECTURER',status:'ACTIVE',pageSize:100}),getUsers({role:'STUDENT',status:'ACTIVE',pageSize:100})]).then(([f,l,s])=>{setFaculties(f.data.items||[]);setLecturers(l.data.items||[]);setAllStudents(s.data.items||[])}).catch(e=>setMessage({type:'error',text:e.message}))},[isClass])
 const create=()=>{setEditing(null);setForm(config.empty);setErrors({});setOpen(true)}
 const edit=item=>{setEditing(item);setErrors({});setForm(isClass?{classCode:item.classCode||'',className:item.className||'',facultyId:item.facultyId||'',admissionYear:item.admissionYear||'',academicProgram:item.academicProgram||'',advisorLecturerId:item.advisorLecturerId||'',description:item.description||''}:{facultyCode:item.facultyCode||'',facultyName:item.facultyName||'',description:item.description||''});setOpen(true)}
 const submit=async event=>{event.preventDefault();if(saving)return;try{setSaving(true);setErrors({});editing?await api.updateOrganization(config.resource,editing.id,form):await api.createOrganization(config.resource,form);setOpen(false);setMessage({type:'success',text:editing?'Cập nhật thành công.':'Thêm mới thành công.'});await load()}catch(e){setErrors(e.errors||{});setMessage({type:'error',text:e.message})}finally{setSaving(false)}}
 const toggle=async item=>{try{await api.setOrganizationStatus(config.resource,item.id,!item.isActive);setMessage({type:'success',text:'Đã cập nhật trạng thái.'});await load()}catch(e){setMessage({type:'error',text:e.message})}}
 const remove=async()=>{try{setSaving(true);await api.deleteOrganization(config.resource,confirm.id);setConfirm(null);setMessage({type:'success',text:'Đã xóa dữ liệu.'});await load()}catch(e){setConfirm(null);setMessage({type:'error',text:e.message})}finally{setSaving(false)}}
 const loadStudents=async item=>{try{setStudentBusy(true);const r=await api.listAdministrativeStudents(item.id,{pageSize:100});setStudents(r.data.items||[])}catch(e){setMessage({type:'error',text:e.message})}finally{setStudentBusy(false)}}
 const showStudents=async item=>{setClassForStudents(item);setStudentId('');await loadStudents(item)}
 const assign=async()=>{if(!studentId)return;try{setStudentBusy(true);await api.assignAdministrativeStudent(classForStudents.id,Number(studentId));setStudentId('');await loadStudents(classForStudents);await load();setMessage({type:'success',text:'Đã gán hoặc chuyển sinh viên.'})}catch(e){setMessage({type:'error',text:e.message})}finally{setStudentBusy(false)}}
 const detach=async id=>{try{setStudentBusy(true);await api.removeAdministrativeStudent(classForStudents.id,id);await loadStudents(classForStudents);await load()}catch(e){setMessage({type:'error',text:e.message})}finally{setStudentBusy(false)}}
 const actions=item=><div className="compact-actions"><button onClick={()=>edit(item)}>Sửa</button><button onClick={()=>toggle(item)}>{item.isActive?'Tắt':'Bật'}</button>{isClass&&<button onClick={()=>showStudents(item)}><Users size={14}/> Sinh viên</button>}<button className="danger-link" aria-label="Xóa" onClick={()=>setConfirm(item)}><Trash2 size={14}/></button></div>
 const columns=isClass?[{key:'classCode',label:'Mã lớp'},{key:'className',label:'Tên lớp'},{key:'facultyName',label:'Khoa'},{key:'admissionYear',label:'Năm nhập học',render:r=>r.admissionYear||'—'},{key:'academicProgram',label:'Chương trình/ngành',render:r=>r.academicProgram||'—'},{key:'advisorLecturerName',label:'Cố vấn',render:r=>r.advisorLecturerName||'—'},{key:'studentCount',label:'Sinh viên'},{key:'status',label:'Trạng thái',render:r=><span className={`status-pill ${r.isActive?'active':'inactive'}`}>{r.isActive?'Hoạt động':'Ngừng hoạt động'}</span>},{key:'actions',label:'Thao tác',render:actions}]:[{key:'facultyCode',label:'Mã khoa'},{key:'facultyName',label:'Tên khoa'},{key:'description',label:'Mô tả',render:r=>r.description||'—'},{key:'administrativeClassCount',label:'Số lớp'},{key:'status',label:'Trạng thái',render:r=><span className={`status-pill ${r.isActive?'active':'inactive'}`}>{r.isActive?'Hoạt động':'Ngừng hoạt động'}</span>},{key:'updatedAt',label:'Cập nhật',render:r=>formatDate(r.updatedAt||r.createdAt)},{key:'actions',label:'Thao tác',render:actions}]
 return <div className="admin-page organization-page"><PageHeader eyebrow="Quản lý học vụ" title={`Quản lý ${config.title.toLowerCase()}`} description={isClass?'Lớp hành chính độc lập với lớp học phần.':'Danh mục khoa của trường.'} actions={<button className="btn-primary small" onClick={create}><Plus size={18}/>Thêm mới</button>}/>{message&&<div className={`alert ${message.type}`}>{message.text}<button onClick={()=>setMessage(null)}>×</button></div>}
 <section className="panel"><form className="organization-filters" onSubmit={e=>{e.preventDefault();setPage(1);load()}}><label className="search-field"><Search size={18}/><input aria-label="Tìm kiếm" placeholder="Tìm theo mã hoặc tên" value={search} onChange={e=>setSearch(e.target.value)}/></label>{isClass&&<><select aria-label="Lọc khoa" value={facultyFilter} onChange={e=>{setFacultyFilter(e.target.value);setPage(1)}}><option value="">Tất cả khoa</option>{faculties.map(f=><option key={f.id} value={f.id}>{f.facultyCode} — {f.facultyName}</option>)}</select><input aria-label="Năm nhập học" type="number" placeholder="Năm nhập học" value={yearFilter} onChange={e=>{setYearFilter(e.target.value);setPage(1)}}/></>}<select aria-label="Trạng thái" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Tất cả trạng thái</option><option value="true">Hoạt động</option><option value="false">Ngừng hoạt động</option></select><button className="btn-primary small">Tìm</button></form>{loadError?<ErrorState message={loadError} onRetry={load}/>:<DataTable columns={columns} rows={items} loading={loading} emptyTitle={`Chưa có ${config.title.toLowerCase()}`}/>}<div className="pagination-bar"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Trước</button><span>Trang {page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)}>Sau</button></div></section>
 <Modal open={open} title={`${editing?'Cập nhật':'Thêm'} ${config.title.toLowerCase()}`} onClose={()=>!saving&&setOpen(false)} closeOnBackdrop={!saving} closeOnEscape={!saving}><form className="modal-form" onSubmit={submit}><div className="form-grid modal-form-grid">{isClass?<><FormField label="Mã lớp" required error={errors.classCode?.[0]}><input value={form.classCode} maxLength="50" onChange={e=>setForm({...form,classCode:e.target.value})}/></FormField><FormField label="Tên lớp" required error={errors.className?.[0]}><input value={form.className} maxLength="100" onChange={e=>setForm({...form,className:e.target.value})}/></FormField><FormField label="Khoa" required error={errors.facultyId?.[0]}><select value={form.facultyId} onChange={e=>setForm({...form,facultyId:e.target.value})}><option value="">-- Chọn khoa --</option>{faculties.map(f=><option key={f.id} value={f.id}>{f.facultyCode} — {f.facultyName}</option>)}</select></FormField><FormField label="Năm nhập học" error={errors.admissionYear?.[0]}><input type="number" min="1900" max="2200" value={form.admissionYear} onChange={e=>setForm({...form,admissionYear:e.target.value})}/></FormField><FormField label="Chương trình/ngành"><input value={form.academicProgram} maxLength="150" onChange={e=>setForm({...form,academicProgram:e.target.value})}/></FormField><FormField label="Cố vấn học tập" error={errors.advisorLecturerId?.[0]}><select value={form.advisorLecturerId} onChange={e=>setForm({...form,advisorLecturerId:e.target.value})}><option value="">Chưa phân công</option>{lecturers.map(l=><option key={l.id} value={l.id}>{l.userCode||l.email} — {l.fullName}</option>)}</select></FormField><FormField label="Mô tả"><textarea value={form.description} maxLength="500" onChange={e=>setForm({...form,description:e.target.value})}/></FormField></>:<><FormField label="Mã khoa" required error={errors.facultyCode?.[0]}><input value={form.facultyCode} maxLength="30" onChange={e=>setForm({...form,facultyCode:e.target.value})}/></FormField><FormField label="Tên khoa" required error={errors.facultyName?.[0]}><input value={form.facultyName} maxLength="150" onChange={e=>setForm({...form,facultyName:e.target.value})}/></FormField><FormField label="Mô tả"><textarea value={form.description} maxLength="500" onChange={e=>setForm({...form,description:e.target.value})}/></FormField></>}</div><footer className="modal-actions"><button type="button" className="btn-light" disabled={saving} onClick={()=>setOpen(false)}>Hủy</button><button className="btn-primary small" disabled={saving}>{saving?'Đang lưu...':'Lưu thay đổi'}</button></footer></form></Modal>
 <ConfirmModal open={Boolean(confirm)} title={`Xóa ${config.title.toLowerCase()}?`} description="Không thể xóa dữ liệu đang được tham chiếu." loading={saving} onClose={()=>!saving&&setConfirm(null)} onConfirm={remove}/>
 <Modal open={Boolean(classForStudents)} title={`Sinh viên lớp ${classForStudents?.classCode||''}`} description="Gán hoặc chuyển sinh viên; ghi danh lớp học phần không bị ảnh hưởng." onClose={()=>!studentBusy&&setClassForStudents(null)}><div className="student-assignment"><div className="assignment-row"><select value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">-- Chọn sinh viên --</option>{allStudents.map(s=><option key={s.id} value={s.id}>{s.userCode||s.email} — {s.fullName}</option>)}</select><button className="btn-primary small" disabled={!studentId||studentBusy} onClick={assign}>Gán/chuyển</button></div><DataTable loading={studentBusy} rows={students} emptyTitle="Lớp chưa có sinh viên" columns={[{key:'studentCode',label:'Mã sinh viên'},{key:'fullName',label:'Họ tên'},{key:'email',label:'Email'},{key:'actions',label:'Thao tác',render:r=><button className="btn-light" onClick={()=>detach(r.studentId)}>Xóa khỏi lớp</button>}]}/></div></Modal></div>
}
