import * as repo from './groups.repository.js';
const ok=(data,message,statusCode=200)=>({success:true,data,message,statusCode});
const fail=(statusCode,message,errors=null)=>({success:false,statusCode,message,errors});
const idOf=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null;};
const clean=v=>String(v??'').trim();
async function authorize(groupId,user,leader=false){const id=idOf(groupId);if(!id)return{error:fail(400,'Id nhóm không hợp lệ')};const group=await repo.findGroup(id);if(!group)return{error:fail(404,'Không tìm thấy nhóm')};if(user.role==='ADMIN')return{group};if(user.role==='LECTURER'){const a=await repo.getClassAccess(group.classId,user.id);return a?.lecturerId===user.id?{group}:{error:fail(403,'Bạn không phụ trách lớp học phần này')}}const mine=await repo.findMyGroup(user.id,group.classId);if(!mine||mine.id!==group.id)return{error:fail(403,'Bạn không thuộc nhóm này')};if(leader&&group.leaderId!==user.id)return{error:fail(403,'Chỉ trưởng nhóm được thực hiện thao tác này')};return{group};}
export async function createGroup(classId,b,user){const cid=idOf(classId),name=clean(b.name),maxMembers=b.maxMembers===undefined?5:Number(b.maxMembers);if(user.role!=='STUDENT')return fail(403,'Chỉ sinh viên được tạo nhóm');if(!cid||!name||!Number.isInteger(maxMembers)||maxMembers<2||maxMembers>20)return fail(400,'Tên nhóm và giới hạn 2-20 thành viên là bắt buộc');const a=await repo.getClassAccess(cid,user.id);if(!a?.isStudent)return fail(403,'Bạn chưa tham gia lớp học phần này');if(await repo.findMyGroup(user.id,cid))return fail(409,'Bạn đã thuộc một nhóm trong lớp');return ok(await repo.createGroup({classId:cid,name,leaderId:user.id,maxMembers}),'Tạo nhóm thành công',201);}
export async function getGroups(classId,user){const cid=idOf(classId),a=cid&&await repo.getClassAccess(cid,user.id);if(!a)return fail(404,'Không tìm thấy lớp học phần');if(user.role==='LECTURER'&&a.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp học phần này');if(user.role==='STUDENT'&&!a.isStudent)return fail(403,'Bạn chưa tham gia lớp học phần này');return ok(await repo.listGroups(cid,user),'Lấy danh sách nhóm thành công');}
export async function getGroup(id,user){const a=await authorize(id,user);return a.error||ok({...a.group,members:await repo.listMembers(a.group.id)},'Lấy nhóm thành công');}
export async function getMyGroup(user,classId){const g=await repo.findMyGroup(user.id,idOf(classId));return g?ok({...g,members:await repo.listMembers(g.id),topicRegistration:await repo.findTopicByGroup(g.id)},'Lấy nhóm của bạn thành công'):fail(404,'Bạn chưa thuộc nhóm nào');}
export async function addMember(id,b,user){const a=await authorize(id,user,true),sid=idOf(b.studentId);if(a.error)return a.error;if(!sid)return fail(400,'Id sinh viên không hợp lệ');try{return ok(await repo.addMember(a.group,sid),'Thêm thành viên thành công')}catch(e){if(e.number>=50001&&e.number<=50005)return fail(409,e.message);throw e}}
export async function removeMember(id,s,user){const a=await authorize(id,user,true),sid=idOf(s);if(a.error)return a.error;if(sid===a.group.leaderId)return fail(409,'Phải chuyển quyền trưởng nhóm trước khi xóa trưởng nhóm');return await repo.removeMember(a.group.id,sid)?ok(null,'Xóa thành viên thành công'):fail(404,'Không tìm thấy thành viên');}
export async function transferLeader(id,b,user){const a=await authorize(id,user,true),sid=idOf(b.studentId);if(a.error)return a.error;if(!sid)return fail(400,'Id trưởng nhóm mới không hợp lệ');try{return ok(await repo.transferLeader(a.group.id,sid),'Chuyển trưởng nhóm thành công')}catch(e){if(e.number===50005)return fail(409,e.message);throw e}}
export async function getTopic(id,user){const a=await authorize(id,user);if(a.error)return a.error;const t=await repo.findTopicByGroup(a.group.id);return t?ok(t,'Lấy đăng ký đề tài thành công'):fail(404,'Nhóm chưa đăng ký đề tài');}
export async function saveTopic(id,b,user){const a=await authorize(id,user,true);if(a.error)return a.error;const title=clean(b.title),description=clean(b.description);if(!title||!description)return fail(400,'Tên và mô tả đề tài là bắt buộc');const current=await repo.findTopicByGroup(a.group.id);if(current&&!['PENDING','REQUIRES_REVISION'].includes(current.status))return fail(409,'Không thể chỉnh sửa ở trạng thái hiện tại');try{return ok(await repo.saveTopic(a.group,{...b,title,description},current?.id),current?'Cập nhật đề tài thành công':'Đăng ký đề tài thành công',current?200:201)}catch(e){if([2601,2627].includes(e.number))return fail(409,'Tên đề tài đã tồn tại trong lớp');throw e}}
export async function listTopics(user,status){const s=status?clean(status).toUpperCase():null;if(s&&!['PENDING','APPROVED','REJECTED','REQUIRES_REVISION'].includes(s))return fail(400,'Trạng thái không hợp lệ');return ok(await repo.listLecturerTopics(user.id,s),'Lấy danh sách đề tài thành công');}
export async function getLecturerTopic(id,user){const t=await repo.findTopic(idOf(id));if(!t)return fail(404,'Không tìm thấy đăng ký');return t.lecturerId===user.id?ok(t,'Lấy đăng ký thành công'):fail(403,'Bạn không phụ trách lớp này');}
export async function reviewTopic(id,b,user){const t=await repo.findTopic(idOf(id));if(!t)return fail(404,'Không tìm thấy đăng ký');if(t.lecturerId!==user.id)return fail(403,'Bạn không phụ trách lớp này');const status=clean(b.status).toUpperCase(),comment=clean(b.comment);if(!['APPROVED','REJECTED','REQUIRES_REVISION'].includes(status))return fail(400,'Trạng thái duyệt không hợp lệ');if(status!=='APPROVED'&&!comment)return fail(400,'Phải nhập lý do');return ok(await repo.reviewTopic(t,status,comment,user.id),'Duyệt đề tài thành công');}
