import test from "node:test";
import assert from "node:assert/strict";
import sql from "mssql";
import { poolPromise } from "../../src/config/db.js";
import { cleanupRegressionData, createCsvFile, createRecorder, createRegressionContext, csvForm, loginAs, lookupDemoUsers, printSummary, requestAs } from "./helpers.js";

test("course CSV new-only policy, capacity and atomic conflict",{timeout:60_000},async()=>{
 const recorder=createRecorder(),context=createRegressionContext();let cleanup;
 try{
  const admin=await loginAs(recorder,"admin.demo@tvu.edu.vn",process.env.DEMO_ADMIN_PASSWORD,"ADMIN"),users=await lookupDemoUsers(),now=Date.now(),iso=o=>new Date(now+o).toISOString(),code=`REG${context.runId}`,password=process.env.DEMO_STUDENT_PASSWORD,headers=["studentCode","fullName","email","password"];
  const year=(await requestAs(recorder,"/academic-years",{token:admin.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_YEAR`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data;
  const semester=(await requestAs(recorder,"/semesters",{token:admin.accessToken,method:"POST",expected:[201],body:{academicYearId:year.id,name:`${context.prefix}_SEM`,code:`${context.prefix}_SEM`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data;
  const subject=(await requestAs(recorder,"/subjects",{token:admin.accessToken,method:"POST",expected:[201],body:{code:`${context.prefix}_SUB`,name:`${context.prefix}_SUBJECT`,credits:3}})).data;
  async function course(suffix,maxStudents){return(await requestAs(recorder,"/course-classes",{token:admin.accessToken,method:"POST",expected:[201],body:{subjectId:subject.id,semesterId:semester.id,lecturerId:users.get("GV001").id,maxStudents,status:"ACTIVE",allowSelfEnrollment:true,enrollmentOpenAt:iso(-86400000),enrollmentCloseAt:iso(86400000)}})).data}
  const freshCourse=await course("FRESH",10),policyCourse=await course("POLICY",10),capacityCourse=await course("CAPACITY",1),atomicCourse=await course("ATOMIC",10);
  const freshRows=[[`${code}N1`,"Sinh viên Nguyễn Ánh",`${code.toLowerCase()}n1@example.test`,password],[`${code}N2`,"Sinh viên Trần Đức",`${code.toLowerCase()}n2@example.test`,password]];
  const freshFile=await createCsvFile(context,"fresh.csv",headers,freshRows),freshPreview=await requestAs(recorder,"/admin/students/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(freshFile.path,{courseClassId:freshCourse.id})});assert.equal(freshPreview.data.validCount,2);
  const freshConfirm=await requestAs(recorder,"/admin/students/import-confirm",{token:admin.accessToken,method:"POST",expected:[201],body:{previewId:freshPreview.data.previewId,courseClassId:freshCourse.id,mode:"atomic"}});assert.equal(freshConfirm.data.createdCount,2);assert.ok(freshConfirm.data.students.every(x=>!Object.hasOwn(x,"passwordHash")&&!Object.hasOwn(x,"PasswordHash")));
  const pool=await poolPromise,freshDb=await pool.request().input("Prefix",sql.NVarChar(50),`${code}N%`).query("SELECT u.Role role,e.EnrollmentSource source FROM Users u JOIN CourseClassEnrollments e ON e.StudentId=u.Id WHERE u.UserCode LIKE @Prefix");assert.equal(freshDb.recordset.length,2);assert.ok(freshDb.recordset.every(x=>x.role==="STUDENT"&&x.source==="CSV_IMPORT"));
  const existingRows=[["SV003","Existing Student","sv003@tvu.edu.vn",password]],existingFile=await createCsvFile(context,"existing.csv",headers,existingRows),existingPreview=await requestAs(recorder,"/admin/students/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(existingFile.path,{courseClassId:policyCourse.id})});assert.equal(existingPreview.data.invalidCount,1);assert.match(existingPreview.data.rows[0].errors.join(" "),/Thêm sinh viên có sẵn/);
  await requestAs(recorder,"/admin/students/import-confirm",{token:admin.accessToken,method:"POST",expected:[409],body:{previewId:existingPreview.data.previewId,courseClassId:policyCourse.id,mode:"atomic"}});
  await requestAs(recorder,`/course-classes/${policyCourse.id}/students/bulk`,{token:admin.accessToken,method:"POST",body:{studentIds:[users.get("SV002").id]}});
  const enrolledFile=await createCsvFile(context,"already-enrolled.csv",headers,[["SV002","Already Enrolled","sv002@tvu.edu.vn",password]]),enrolledPreview=await requestAs(recorder,"/admin/students/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(enrolledFile.path,{courseClassId:policyCourse.id})});assert.equal(enrolledPreview.data.invalidCount,1);assert.match(enrolledPreview.data.rows[0].errors.join(" "),/Thêm sinh viên có sẵn/);
  const capRows=[1,2].map(i=>[`${code}C${i}`,`Sinh viên Capacity ${i}`,`${code.toLowerCase()}c${i}@example.test`,password]),capFile=await createCsvFile(context,"capacity.csv",headers,capRows),capPreview=await requestAs(recorder,"/admin/students/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(capFile.path,{courseClassId:capacityCourse.id})});assert.equal(capPreview.data.validCount,2);
  await requestAs(recorder,"/admin/students/import-confirm",{token:admin.accessToken,method:"POST",expected:[409],body:{previewId:capPreview.data.previewId,courseClassId:capacityCourse.id,mode:"atomic"}});
  const capDb=await pool.request().input("Prefix",sql.NVarChar(50),`${code}C%`).query("SELECT (SELECT COUNT(*) FROM Users WHERE UserCode LIKE @Prefix) users,(SELECT COUNT(*) FROM CourseClassEnrollments WHERE CourseClassId="+Number(capacityCourse.id)+") enrollments");assert.deepEqual(Object.values(capDb.recordset[0]).map(Number),[0,0]);
  const atomicRows=[1,2,3].map(i=>[`${code}A${i}`,`Sinh viên Atomic ${i}`,`${code.toLowerCase()}a${i}@example.test`,password]),atomicFile=await createCsvFile(context,"atomic-students.csv",headers,atomicRows),atomicPreview=await requestAs(recorder,"/admin/students/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(atomicFile.path,{courseClassId:atomicCourse.id})});
  await requestAs(recorder,"/users",{token:admin.accessToken,method:"POST",expected:[201],body:{fullName:"Conflict Student",email:atomicRows[1][2],role:"STUDENT",userCode:atomicRows[1][0],password:password,confirmPassword:password}});
  const conflict=await requestAs(recorder,"/admin/students/import-confirm",{token:admin.accessToken,method:"POST",expected:[409],body:{previewId:atomicPreview.data.previewId,courseClassId:atomicCourse.id,mode:"atomic"}});assert.doesNotMatch(conflict.payload.message,/Violation|duplicate key|INSERT|SQL/i);
  const atomicDb=await pool.request().input("Prefix",sql.NVarChar(50),`${code}A%`).query("SELECT u.UserCode code,e.Id enrollmentId FROM Users u LEFT JOIN CourseClassEnrollments e ON e.StudentId=u.Id WHERE u.UserCode LIKE @Prefix");assert.equal(atomicDb.recordset.length,1);assert.equal(atomicDb.recordset[0].code,atomicRows[1][0]);assert.equal(atomicDb.recordset[0].enrollmentId,null);
 }finally{cleanup=await cleanupRegressionData(context);printSummary("course-csv-policy",recorder,cleanup);}
});
