import test from"node:test";import assert from"node:assert/strict";import{cleanupRegressionData,createRecorder,createRegressionContext,loginAs,lookupDemoUsers,printSummary,requestAs}from"./helpers.js";
test("course transfer success and rollback matrix",{timeout:45_000},async()=>{const recorder=createRecorder(),context=createRegressionContext();let cleanup;try{
 const admin=await loginAs(recorder,"admin.demo@tvu.edu.vn",process.env.DEMO_ADMIN_PASSWORD,"ADMIN"),student=await loginAs(recorder,"sv001@tvu.edu.vn",process.env.DEMO_STUDENT_PASSWORD,"STUDENT"),lecturer=await loginAs(recorder,"thiennhd@tvu.edu.vn",process.env.DEMO_LECTURER_PASSWORD,"LECTURER"),student2=await loginAs(recorder,"sv002@tvu.edu.vn",process.env.DEMO_STUDENT_PASSWORD,"STUDENT"),users=await lookupDemoUsers(),now=Date.now(),iso=o=>new Date(now+o).toISOString();
 const year=(await requestAs(recorder,"/academic-years",{token:admin.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_YEAR`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data;
 async function semester(suffix){return(await requestAs(recorder,"/semesters",{token:admin.accessToken,method:"POST",expected:[201],body:{academicYearId:year.id,name:suffix==="B"?`Học kỳ 2 ${context.prefix}`:`Học kỳ 1 ${context.prefix}`,code:`${context.prefix}_SEM_${suffix}`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data}
 const sem1=await semester("A"),sem2=await semester("B");
 async function subject(suffix){return(await requestAs(recorder,"/subjects",{token:admin.accessToken,method:"POST",expected:[201],body:{code:`${context.prefix}_SUB_${suffix}`,name:`${context.prefix}_SUBJECT_${suffix}`,credits:3}})).data}
 const sub1=await subject("A"),sub2=await subject("B");
 async function cls(subjectId,semesterId,capacity=10){return(await requestAs(recorder,"/course-classes",{token:admin.accessToken,method:"POST",expected:[201],body:{subjectId,semesterId,lecturerId:users.get("GV001").id,maxStudents:capacity,status:"ACTIVE",allowSelfEnrollment:true,enrollmentOpenAt:iso(-86400000),enrollmentCloseAt:iso(86400000)}})).data}
 const source=await cls(sub1.id,sem1.id),target=await cls(sub1.id,sem1.id),full=await cls(sub1.id,sem1.id,1),otherSubject=await cls(sub2.id,sem1.id),otherSemester=await cls(sub1.id,sem2.id),groupTarget=await cls(sub1.id,sem1.id);
 const bulk=(courseId,ids)=>requestAs(recorder,`/course-classes/${courseId}/students/bulk`,{token:admin.accessToken,method:"POST",body:{studentIds:ids}});
 await bulk(source.id,[users.get("SV001").id]);await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",body:{studentId:users.get("SV001").id,sourceCourseClassId:source.id,targetCourseClassId:target.id,reason:"REG transfer"}});
 await requestAs(recorder,`/student/course-classes/${source.id}`,{token:student.accessToken,expected:[404]});await requestAs(recorder,`/student/course-classes/${target.id}`,{token:student.accessToken});
 await bulk(source.id,[users.get("SV002").id]);await bulk(target.id,[users.get("SV002").id]);await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[409],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:target.id,reason:"REG existing"}});await bulk(full.id,[users.get("SV003").id]);
 await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[409],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:full.id,reason:"REG full"}});
 const sourceList=await requestAs(recorder,`/course-classes/${source.id}/students?pageSize=100`,{token:admin.accessToken});assert.ok(sourceList.data.items.some(x=>x.studentCode==="SV002"));
 await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[409],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:otherSubject.id,reason:"REG subject"}});
 await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[409],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:otherSemester.id,reason:"REG semester"}});
 await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[404,409],body:{studentId:users.get("SV003").id,sourceCourseClassId:source.id,targetCourseClassId:target.id,reason:"REG missing"}});
 await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[404],body:{studentId:users.get("SV002").id,sourceCourseClassId:2147483000,targetCourseClassId:target.id,reason:"REG missing source"}});await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[404],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:2147483000,reason:"REG missing target"}});await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[404],body:{studentId:users.get("SV002").id,sourceCourseClassId:2147483000,targetCourseClassId:2147483001,reason:"REG both missing"}});const group=(await requestAs(recorder,`/course-classes/${source.id}/groups`,{token:student2.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_TRANSFER_GROUP`,maxMembers:5}})).data;const locked=await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[409],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:groupTarget.id,reason:"REG group lock"}});assert.match(locked.payload.message,/nhóm/i);const sourceAfter=await requestAs(recorder,`/course-classes/${source.id}/students?pageSize=100`,{token:admin.accessToken}),targetAfter=await requestAs(recorder,`/course-classes/${target.id}/students?pageSize=100`,{token:admin.accessToken}),groupTargetAfter=await requestAs(recorder,`/course-classes/${groupTarget.id}/students?pageSize=100`,{token:admin.accessToken}),groupAfter=await requestAs(recorder,`/groups/${group.id}`,{token:student2.accessToken});assert.equal(sourceAfter.data.items.filter(x=>x.studentCode==="SV002").length,1);assert.equal(targetAfter.data.items.filter(x=>x.studentCode==="SV002").length,1);assert.equal(groupTargetAfter.data.items.filter(x=>x.studentCode==="SV002").length,0);assert.equal(groupAfter.data.members.filter(x=>x.studentId===users.get("SV002").id).length,1);
 for(const token of[student.accessToken,lecturer.accessToken])await requestAs(recorder,"/admin/course-enrollments/transfer",{token,method:"POST",expected:[403],body:{studentId:users.get("SV002").id,sourceCourseClassId:source.id,targetCourseClassId:target.id,reason:"REG role"}});
}finally{cleanup=await cleanupRegressionData(context);printSummary("course-transfer",recorder,cleanup);}});
