import test from"node:test";import assert from"node:assert/strict";import{cleanupRegressionData,createCsvFile,createRecorder,createRegressionContext,createTestFile,csvForm,loginAs,printSummary,requestAs}from"./helpers.js";
test("CSV headers, empty files, row/size limits and atomic confirm",{timeout:60_000},async()=>{const recorder=createRecorder(),context=createRegressionContext();let cleanup;try{
 const admin=await loginAs(recorder,"admin.demo@tvu.edu.vn",process.env.DEMO_ADMIN_PASSWORD,"ADMIN"),code=`REG${context.runId}`,lecturerPassword=process.env.DEMO_LECTURER_PASSWORD,headers=["lecturerCode","fullName","email","password"],valid=[`${code}V`,"Giảng viên Ánh",`${code.toLowerCase()}v@example.test`,lecturerPassword];
 for(const missing of headers){const selected=headers.filter(x=>x!==missing),row=selected.map(x=>valid[headers.indexOf(x)]),file=await createCsvFile(context,`missing-${missing}.csv`,selected,[row]);await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",expected:[400],body:await csvForm(file.path)});}
 const wrong=await createCsvFile(context,"wrong-header.csv",["lecturer_code","fullName","email","password"],[[...valid]]);await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",expected:[400],body:await csvForm(wrong.path)});
 for(const[fileName,content]of[["zero.csv",Buffer.alloc(0)],["blank.csv","   \r\n"],["bom.csv","\uFEFF"],["header.csv",`\uFEFF${headers.join(",")}\r\n`]]){const file=await createTestFile(context,fileName,content);await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",expected:[400],body:await csvForm(file.path)});}
 const rows=n=>Array.from({length:n},(_,i)=>[`${code}R${i}`,`Giảng viên ${i}`,`${code.toLowerCase()}r${i}@example.test`,lecturerPassword]);
 const fiveHundred=await createCsvFile(context,"500.csv",headers,rows(500)),preview500=await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(fiveHundred.path)});assert.equal(preview500.data.totalRows,500);assert.equal(preview500.data.validCount,500);
 const fiveOhOne=await createCsvFile(context,"501.csv",headers,rows(501));await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",expected:[413],body:await csvForm(fiveOhOne.path)});
 const overSize=await createTestFile(context,"over-2mb.csv",Buffer.alloc(2*1024*1024+1,65));await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",expected:[413],body:await csvForm(overSize.path)});
 const atomicRows=[1,2,3].map(i=>[`${code}A${i}`,`Giảng viên Atomic ${i}`,`${code.toLowerCase()}a${i}@example.test`,lecturerPassword]),atomicFile=await createCsvFile(context,"atomic.csv",headers,atomicRows),atomicPreview=await requestAs(recorder,"/admin/lecturers/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(atomicFile.path)});
 await requestAs(recorder,"/users",{token:admin.accessToken,method:"POST",expected:[201],body:{fullName:"Conflict Lecturer",email:atomicRows[1][2],role:"LECTURER",userCode:atomicRows[1][0],password:lecturerPassword,confirmPassword:lecturerPassword}});
 await requestAs(recorder,"/admin/lecturers/import-confirm",{token:admin.accessToken,method:"POST",expected:[409],body:{previewId:atomicPreview.data.previewId,mode:"atomic"}});
 const after=await requestAs(recorder,`/users?search=${code}A&pageSize=100`,{token:admin.accessToken});assert.equal(after.data.items.length,1);assert.equal(after.data.items[0].userCode,atomicRows[1][0]);
}finally{cleanup=await cleanupRegressionData(context);printSummary("csv-boundaries",recorder,cleanup);}});
