import test from"node:test";import assert from"node:assert/strict";import{poolPromise}from"../../src/config/db.js";import{cleanupRegressionData,createCsvFile,createRecorder,createRegressionContext,csvForm,loginAs,lookupDemoUsers,printSummary,requestAs}from"./helpers.js";
test("one student has ADMIN, CSV_IMPORT and SELF_ENROLLMENT in one semester",{timeout:45_000},async()=>{const recorder=createRecorder(),context=createRegressionContext();let cleanup;try{
 const admin=await loginAs(recorder,"admin.demo@tvu.edu.vn",process.env.DEMO_ADMIN_PASSWORD,"ADMIN"),users=await lookupDemoUsers(),now=Date.now(),iso=o=>new Date(now+o).toISOString(),code=`REG${context.runId}`;
 const year=(await requestAs(recorder,"/academic-years",{token:admin.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_YEAR`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data,sem=(await requestAs(recorder,"/semesters",{token:admin.accessToken,method:"POST",expected:[201],body:{academicYearId:year.id,name:`Học kỳ 1 ${context.prefix}`,code:`${context.prefix}_SEM`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data;
 async function course(suffix){const sub=(await requestAs(recorder,"/subjects",{token:admin.accessToken,method:"POST",expected:[201],body:{code:`${context.prefix}_S${suffix}`,name:`${context.prefix}_SUB_${suffix}`,credits:3}})).data;return(await requestAs(recorder,"/course-classes",{token:admin.accessToken,method:"POST",expected:[201],body:{subjectId:sub.id,semesterId:sem.id,lecturerId:users.get("GV001").id,maxStudents:10,status:"ACTIVE",allowSelfEnrollment:true,enrollmentOpenAt:iso(-86400000),enrollmentCloseAt:iso(86400000)}})).data}
 const a=await course("A"),b=await course("B"),c=await course("C"),d=await course("D"),studentCode=`${code}SV`,email=`${code.toLowerCase()}sv@example.test`,password=process.env.DEMO_STUDENT_PASSWORD;
 const csv=await createCsvFile(context,"multi.csv",["studentCode","fullName","email","password"],[[studentCode,"Sinh viên Đa lớp",email,password]]),preview=await requestAs(recorder,"/admin/students/import-preview",{token:admin.accessToken,method:"POST",body:await csvForm(csv.path,{courseClassId:b.id})});await requestAs(recorder,"/admin/students/import-confirm",{token:admin.accessToken,method:"POST",expected:[201],body:{previewId:preview.data.previewId,courseClassId:b.id,mode:"atomic"}});
 const student=await loginAs(recorder,email,password,"STUDENT"),studentId=student.user.id;await requestAs(recorder,`/course-classes/${a.id}/students/bulk`,{token:admin.accessToken,method:"POST",body:{studentIds:[studentId]}});await requestAs(recorder,`/student/course-class-enrollment/${c.id}`,{token:student.accessToken,method:"POST",expected:[201]});
 const rows=(await(await poolPromise).request().input("Uid",(await import("mssql")).default.Int,studentId).query("SELECT CourseClassId classId,EnrollmentSource source FROM CourseClassEnrollments WHERE StudentId=@Uid AND EnrollmentStatus='ACTIVE' AND IsActive=1 AND DeletedAt IS NULL")).recordset;assert.equal(rows.length,3);assert.deepEqual(new Set(rows.map(x=>x.source)),new Set(["ADMIN","CSV_IMPORT","SELF_ENROLLMENT"]));
 const list=await requestAs(recorder,"/student/course-classes?pageSize=100",{token:student.accessToken});assert.ok([a.id,b.id,c.id].every(id=>list.data.items.some(x=>x.id===id)));await requestAs(recorder,`/student/course-classes/${d.id}`,{token:student.accessToken,expected:[404]});
}finally{cleanup=await cleanupRegressionData(context);printSummary("multi-enrollment",recorder,cleanup);}});
