import test from "node:test";
import assert from "node:assert/strict";
import sql from "mssql";
import { poolPromise } from "../../src/config/db.js";
import {
  cleanupRegressionData, createRecorder, createRegressionContext, createTestFile,
  fileForm, loginAs, lookupDemoUsers, printSummary, requestAs, requestDownload,
} from "./helpers.js";

test("topic rounds, files, registration, review, notifications and group policy",{timeout:120_000},async()=>{
 const recorder=createRecorder(),context=createRegressionContext();let cleanup;
 try{
  const lecturer=await loginAs(recorder,"thiennhd@tvu.edu.vn",process.env.DEMO_LECTURER_PASSWORD,"LECTURER"),otherLecturer=await loginAs(recorder,"annb@tvu.edu.vn",process.env.DEMO_LECTURER_PASSWORD,"LECTURER"),admin=await loginAs(recorder,"admin.demo@tvu.edu.vn",process.env.DEMO_ADMIN_PASSWORD,"ADMIN"),leader=await loginAs(recorder,"sv001@tvu.edu.vn",process.env.DEMO_STUDENT_PASSWORD,"STUDENT"),member=await loginAs(recorder,"sv002@tvu.edu.vn",process.env.DEMO_STUDENT_PASSWORD,"STUDENT"),outside=await loginAs(recorder,"sv003@tvu.edu.vn",process.env.DEMO_STUDENT_PASSWORD,"STUDENT");
  const users=await lookupDemoUsers(),pool=await poolPromise,now=Date.now(),iso=o=>new Date(now+o).toISOString(),roundBody=(classId,name,start=-3600000,end=86400000)=>({classId,name,description:`Mô tả ${name}`,requirements:"Nộp đúng hạn",allowEditing:true,maxEditCount:5,startAt:iso(start),endAt:iso(end)});
  const year=(await requestAs(recorder,"/academic-years",{token:admin.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_YEAR`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data,semester=(await requestAs(recorder,"/semesters",{token:admin.accessToken,method:"POST",expected:[201],body:{academicYearId:year.id,name:`${context.prefix}_SEM`,code:`${context.prefix}_SEM`,startDate:iso(-86400000),endDate:iso(31536000000)}})).data,subject=(await requestAs(recorder,"/subjects",{token:admin.accessToken,method:"POST",expected:[201],body:{code:`${context.prefix}_SUB`,name:`${context.prefix}_SUBJECT`,credits:3}})).data;
  async function course(lecturerId){return(await requestAs(recorder,"/course-classes",{token:admin.accessToken,method:"POST",expected:[201],body:{subjectId:subject.id,semesterId:semester.id,lecturerId,maxStudents:20,status:"ACTIVE",allowSelfEnrollment:true,enrollmentOpenAt:iso(-86400000),enrollmentCloseAt:iso(86400000)}})).data}
  const classA=await course(users.get("GV001").id),classB=await course(users.get("GV001").id),wrongClass=await course(users.get("GV002").id);
  const password=process.env.DEMO_STUDENT_PASSWORD,studentCode=`REG${context.runId}SV`,studentEmail=`reg${context.runId}sv@example.test`;
  await requestAs(recorder,"/users",{token:admin.accessToken,method:"POST",expected:[201],body:{fullName:"Sinh viên Regression",email:studentEmail,role:"STUDENT",userCode:studentCode,password,confirmPassword:password}});
  const extra=await loginAs(recorder,studentEmail,password,"STUDENT");
  const enroll=(classId,studentIds)=>requestAs(recorder,`/course-classes/${classId}/students/bulk`,{token:admin.accessToken,method:"POST",body:{studentIds}});
  await enroll(classA.id,[users.get("SV001").id,users.get("SV002").id,extra.user.id]);await enroll(classB.id,[users.get("SV001").id]);
  const group=(await requestAs(recorder,`/course-classes/${classA.id}/groups`,{token:leader.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_GROUP_A`,maxMembers:6}})).data;await requestAs(recorder,`/groups/${group.id}/members`,{token:leader.accessToken,method:"POST",body:{studentId:users.get("SV002").id}});
  const group2=(await requestAs(recorder,`/course-classes/${classA.id}/groups`,{token:extra.accessToken,method:"POST",expected:[201],body:{name:`${context.prefix}_GROUP_B`,maxMembers:4}})).data;

  const main=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:roundBody(classA.id,`${context.prefix}_ROUND_MAIN`)})).data;
  assert.equal(main.classId,classA.id);assert.equal(main.lecturerId,users.get("GV001").id);assert.equal(main.status,"DRAFT");assert.equal(new Date(main.startAt).getTime(),new Date(roundBody(classA.id,"x").startAt).getTime());
  const dbRound=(await pool.request().input("Id",sql.Int,main.id).query("SELECT ClassId classId,CreatedBy createdBy,Status status FROM TopicRegistrationRounds WHERE Id=@Id")).recordset[0];assert.deepEqual(dbRound,{classId:classA.id,createdBy:users.get("GV001").id,status:"DRAFT"});
  const listed=await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken});assert.ok(listed.data.some(x=>x.id===main.id));
  for(const body of[
   {...roundBody(classA.id,`${context.prefix}_TIME_EQ`),startAt:iso(1000),endAt:iso(1000)},
   {...roundBody(classA.id,`${context.prefix}_TIME_AFTER`),startAt:iso(2000),endAt:iso(1000)},
   {...roundBody(classA.id,`${context.prefix}_NO_START`),startAt:undefined},
   {...roundBody(classA.id,`${context.prefix}_NO_END`),endAt:undefined},
   {...roundBody(classA.id,`${context.prefix}_BAD_TIME`),startAt:"not-a-date"},
  ])await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[400],body});
  const timezone=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:{...roundBody(classA.id,`${context.prefix}_TIMEZONE`),startAt:"2026-08-01T08:00:00+07:00",endAt:"2026-08-01T03:00:00Z"}})).data;assert.ok(timezone.id);
  await requestAs(recorder,"/lecturer/topic-rounds",{token:otherLecturer.accessToken,method:"POST",expected:[403],body:roundBody(classA.id,`${context.prefix}_WRONG_CREATE`)});
  await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[403],body:roundBody(wrongClass.id,`${context.prefix}_WRONG_CLASS`)});
  for(const token of[leader.accessToken,admin.accessToken])await requestAs(recorder,"/lecturer/topic-rounds",{token,method:"POST",expected:[403],body:roundBody(classA.id,`${context.prefix}_ROLE`)});
  await requestAs(recorder,"/lecturer/topic-rounds",{method:"POST",expected:[401],body:roundBody(classA.id,`${context.prefix}_NO_AUTH`)});await requestAs(recorder,"/lecturer/topic-rounds",{token:"invalid.token.value",expected:[401]});
  const updated=await requestAs(recorder,`/lecturer/topic-rounds/${main.id}`,{token:lecturer.accessToken,method:"PUT",body:{...roundBody(classA.id,`${context.prefix}_ROUND_UPDATED`),description:"Mô tả đã cập nhật",startAt:iso(-7200000),endAt:iso(172800000)}});assert.equal(updated.data.name,`${context.prefix}_ROUND_UPDATED`);assert.equal(updated.data.description,"Mô tả đã cập nhật");assert.ok(updated.data.updatedAt);
  await requestAs(recorder,`/lecturer/topic-rounds/${main.id}`,{token:otherLecturer.accessToken,method:"PUT",expected:[403],body:roundBody(classA.id,"Wrong")});await requestAs(recorder,"/lecturer/topic-rounds/2147483000",{token:lecturer.accessToken,method:"PUT",expected:[404],body:roundBody(classA.id,"Missing")});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}`,{token:lecturer.accessToken,method:"PUT",expected:[400],body:{...roundBody(classA.id,"Invalid"),endAt:iso(-8000000)}});

  const pdf=await createTestFile(context,"Hướng dẫn đề tài.pdf",Buffer.from("%PDF-1.4\n1 0 obj\n<<>>\nendobj\n%%EOF")),doc=await createTestFile(context,"Biểu mẫu đề tài.doc",Buffer.concat([Buffer.from([0xd0,0xcf,0x11,0xe0,0xa1,0xb1,0x1a,0xe1]),Buffer.from("REG DOC")])),docx=await createTestFile(context,"Mẫu đăng ký đề tài.docx",Buffer.concat([Buffer.from([0x50,0x4b,0x03,0x04]),Buffer.from("REG DOCX")]));
  const pdfMeta=(await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[201],body:await fileForm(pdf.path,"application/pdf","Hướng dẫn đề tài.pdf")})).data,docMeta=(await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[201],body:await fileForm(doc.path,"application/msword","Biểu mẫu đề tài.doc")})).data,docxMeta=(await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[201],body:await fileForm(docx.path,"application/vnd.openxmlformats-officedocument.wordprocessingml.document","Mẫu đăng ký đề tài.docx")})).data;
  const expectedNames=["Hướng dẫn đề tài.pdf","Biểu mẫu đề tài.doc","Mẫu đăng ký đề tài.docx"];for(const[index,meta]of[pdfMeta,docMeta,docxMeta].entries()){assert.equal(meta.roundId,main.id);assert.equal(meta.originalName,expectedNames[index]);assert.ok(meta.sizeBytes>0);assert.ok(!Object.hasOwn(meta,"relativePath")&&!Object.hasOwn(meta,"absolutePath"))}
  const files=await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken});assert.equal(files.data.length,3);
  const lecturerDownload=await requestDownload(recorder,`/lecturer/topic-rounds/files/${pdfMeta.id}/download`,{token:lecturer.accessToken});assert.ok(lecturerDownload.body.length>0);assert.match(lecturerDownload.headers.get("content-type")||"",/pdf/);
  const studentDownload=await requestDownload(recorder,`/student/topic-rounds/files/${docxMeta.id}/download`,{token:leader.accessToken});assert.ok(studentDownload.body.length>0);
  await requestDownload(recorder,`/student/topic-rounds/files/${pdfMeta.id}/download`,{token:outside.accessToken,expected:[403]});
  const invalid=await createTestFile(context,"invalid.txt","not allowed"),fakePdf=await createTestFile(context,"fake.pdf","not a pdf"),zero=await createTestFile(context,"zero.pdf",Buffer.alloc(0)),huge=await createTestFile(context,"huge.pdf",Buffer.concat([Buffer.from("%PDF-"),Buffer.alloc(20*1024*1024,65)]));
  await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[400],body:await fileForm(invalid.path,"text/plain","invalid.txt")});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[400],body:await fileForm(fakePdf.path,"application/pdf","fake.pdf")});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[400],body:await fileForm(zero.path,"application/pdf","zero.pdf")});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[413],body:await fileForm(huge.path,"application/pdf","huge.pdf")});
  await requestAs(recorder,`/lecturer/topic-rounds/2147483000/files`,{token:lecturer.accessToken,method:"POST",expected:[404],body:await fileForm(pdf.path,"application/pdf","missing.pdf")});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:otherLecturer.accessToken,method:"POST",expected:[403],body:await fileForm(pdf.path,"application/pdf","wrong.pdf")});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:leader.accessToken,method:"POST",expected:[403],body:await fileForm(pdf.path,"application/pdf","student.pdf")});await requestDownload(recorder,"/student/topic-rounds/files/2147483000/download",{token:leader.accessToken,expected:[404]});
  const deleteMeta=(await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/files`,{token:lecturer.accessToken,method:"POST",expected:[201],body:await fileForm(pdf.path,"application/pdf","delete-me.pdf")})).data;await requestAs(recorder,`/lecturer/topic-rounds/files/${deleteMeta.id}`,{token:otherLecturer.accessToken,method:"DELETE",expected:[403]});await requestAs(recorder,`/lecturer/topic-rounds/files/${deleteMeta.id}`,{token:leader.accessToken,method:"DELETE",expected:[403]});await requestAs(recorder,`/lecturer/topic-rounds/files/${deleteMeta.id}`,{token:lecturer.accessToken,method:"DELETE"});await requestDownload(recorder,`/lecturer/topic-rounds/files/${deleteMeta.id}/download`,{token:lecturer.accessToken,expected:[404]});await requestAs(recorder,`/lecturer/topic-rounds/files/${deleteMeta.id}`,{token:lecturer.accessToken,method:"DELETE",expected:[404]});

  const beforeRoundUnread=(await requestAs(recorder,"/notifications/unread-count",{token:leader.accessToken})).data.count;
  const opened=await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"OPEN"}});assert.equal(opened.data.status,"OPEN");await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/status`,{token:otherLecturer.accessToken,method:"PATCH",expected:[403],body:{status:"CLOSED"}});
  const afterRoundUnread=(await requestAs(recorder,"/notifications/unread-count",{token:leader.accessToken})).data.count;assert.equal(afterRoundUnread,beforeRoundUnread+1);
  const leaderNotifications=await requestAs(recorder,"/notifications?pageSize=100",{token:leader.accessToken}),roundNotice=leaderNotifications.data.items.find(x=>x.type==="TOPIC_ROUND_OPENED"&&x.relatedEntityId===main.id);assert.ok(roundNotice);assert.equal(roundNotice.relatedEntityType,"TOPIC_ROUND");
  await requestAs(recorder,`/notifications/${roundNotice.id}/read`,{token:leader.accessToken,method:"PATCH"});assert.equal((await requestAs(recorder,"/notifications/unread-count",{token:leader.accessToken})).data.count,afterRoundUnread-1);
  const studentRounds=await requestAs(recorder,"/student/topic-rounds",{token:leader.accessToken});assert.ok(studentRounds.data.some(x=>x.id===main.id&&x.status==="OPEN"));assert.ok(!(await requestAs(recorder,"/student/topic-rounds",{token:outside.accessToken})).data.some(x=>x.classId===classA.id));
  const second=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:roundBody(classA.id,`${context.prefix}_ROUND_SECOND`)})).data;await requestAs(recorder,`/lecturer/topic-rounds/${second.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"OPEN"}});const openCount=Number((await pool.request().input("Id",sql.Int,classA.id).query("SELECT COUNT(*) total FROM TopicRegistrationRounds WHERE ClassId=@Id AND Status='OPEN' AND DeletedAt IS NULL")).recordset[0].total);assert.equal(openCount,2);
  const cancelled=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:roundBody(classA.id,`${context.prefix}_ROUND_CANCELLED`)})).data;await requestAs(recorder,`/lecturer/topic-rounds/${cancelled.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"CANCELLED"}});await requestAs(recorder,`/lecturer/topic-rounds/${cancelled.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"CANCELLED"}});
  const before=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:roundBody(classA.id,`${context.prefix}_ROUND_BEFORE`,3600000,7200000)})).data,after=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:roundBody(classA.id,`${context.prefix}_ROUND_AFTER`,-7200000,-3600000)})).data,cross=(await requestAs(recorder,"/lecturer/topic-rounds",{token:lecturer.accessToken,method:"POST",expected:[201],body:roundBody(classB.id,`${context.prefix}_ROUND_CROSS`)})).data;for(const r of[before,after,cross])await requestAs(recorder,`/lecturer/topic-rounds/${r.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"OPEN"}});
  const topic={title:`${context.prefix}_TOPIC_APPROVE`,description:"Mô tả đề tài",objectives:"Mục tiêu",scope:"Phạm vi",technologies:"Node.js",expectedResults:"Kết quả",referenceUrl:"https://example.test/topic"};
  await requestAs(recorder,`/student/topic-rounds/${main.id}/register`,{token:member.accessToken,method:"POST",expected:[403],body:topic});await requestAs(recorder,`/student/topic-rounds/${main.id}/register`,{token:outside.accessToken,method:"POST",expected:[404],body:topic});await requestAs(recorder,`/student/topic-rounds/${main.id}/register`,{token:lecturer.accessToken,method:"POST",expected:[403],body:topic});await requestAs(recorder,`/student/topic-rounds/${before.id}/register`,{token:leader.accessToken,method:"POST",expected:[409],body:topic});await requestAs(recorder,`/student/topic-rounds/${after.id}/register`,{token:leader.accessToken,method:"POST",expected:[409],body:topic});await requestAs(recorder,`/student/topic-rounds/${cancelled.id}/register`,{token:leader.accessToken,method:"POST",expected:[409],body:topic});await requestAs(recorder,`/student/topic-rounds/${cross.id}/register`,{token:leader.accessToken,method:"POST",expected:[409],body:topic});
  const registration=(await requestAs(recorder,`/student/topic-rounds/${main.id}/register`,{token:leader.accessToken,method:"POST",expected:[201],body:topic})).data;assert.equal(registration.roundId,main.id);assert.equal(registration.groupId,group.id);assert.equal(registration.status,"PENDING");await requestAs(recorder,`/student/topic-rounds/${main.id}/register`,{token:leader.accessToken,method:"POST",expected:[409],body:{...topic,title:"Overwrite attempt"}});
  assert.equal(Number((await pool.request().input("Rid",sql.Int,main.id).input("Gid",sql.Int,group.id).query("SELECT COUNT(*) total FROM TopicRegistrations WHERE RoundId=@Rid AND GroupId=@Gid AND DeletedAt IS NULL")).recordset[0].total),1);
  await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}`,{token:otherLecturer.accessToken,expected:[403]});await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}/review`,{token:otherLecturer.accessToken,method:"PATCH",expected:[403],body:{status:"REQUIRES_REVISION",comment:"Wrong"}});await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}/review`,{token:lecturer.accessToken,method:"PATCH",expected:[400],body:{status:"REQUIRES_REVISION",comment:""}});
  const revision=await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}/review`,{token:lecturer.accessToken,method:"PATCH",body:{status:"REQUIRES_REVISION",comment:"Bổ sung phạm vi"}});assert.equal(revision.data.status,"REQUIRES_REVISION");
  const revisedTopic={...topic,title:`${context.prefix}_TOPIC_REVISED`,description:"Nội dung đã chỉnh sửa"};const resubmitted=await requestAs(recorder,`/student/topic-rounds/${main.id}/registration`,{token:leader.accessToken,method:"PUT",body:revisedTopic});assert.equal(resubmitted.data.status,"PENDING");assert.equal(resubmitted.data.revisionCount,1);await requestAs(recorder,`/student/topic-rounds/${main.id}/registration`,{token:member.accessToken,method:"PUT",expected:[403],body:revisedTopic});
  const approved=await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}/review`,{token:lecturer.accessToken,method:"PATCH",body:{status:"APPROVED",comment:"Đạt yêu cầu"}});assert.equal(approved.data.status,"APPROVED");await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}/review`,{token:lecturer.accessToken,method:"PATCH",expected:[409],body:{status:"APPROVED",comment:"Again"}});await requestAs(recorder,`/student/topic-rounds/${main.id}/registration`,{token:leader.accessToken,method:"PUT",expected:[409],body:revisedTopic});
  const rejectTopic={...topic,title:`${context.prefix}_TOPIC_REJECT`},rejectedRegistration=(await requestAs(recorder,`/student/topic-rounds/${main.id}/register`,{token:extra.accessToken,method:"POST",expected:[201],body:rejectTopic})).data;await requestAs(recorder,`/lecturer/topic-registrations/${rejectedRegistration.id}/review`,{token:lecturer.accessToken,method:"PATCH",body:{status:"REJECTED",comment:"Không phù hợp"}});await requestAs(recorder,`/lecturer/topic-registrations/${rejectedRegistration.id}/review`,{token:lecturer.accessToken,method:"PATCH",body:{status:"REJECTED",comment:"Không phù hợp lần hai"}});
  const approveDetail=await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}`,{token:lecturer.accessToken});assert.equal(approveDetail.data.history.length,2);assert.deepEqual(approveDetail.data.history.map(x=>x.newStatus),["APPROVED","REQUIRES_REVISION"]);assert.ok(approveDetail.data.history.every(x=>x.reviewedBy===users.get("GV001").id));assert.ok(!JSON.stringify(approveDetail.data).match(/passwordHash|accessToken/i));
  const rejectDetail=await requestAs(recorder,`/lecturer/topic-registrations/${rejectedRegistration.id}`,{token:lecturer.accessToken});assert.equal(rejectDetail.data.history.length,2);assert.ok(rejectDetail.data.history.every(x=>x.newStatus==="REJECTED"));
  const topicNotices=(await requestAs(recorder,"/notifications?pageSize=100",{token:leader.accessToken})).data.items.filter(x=>x.relatedEntityType==="TOPIC_REGISTRATION"&&x.relatedEntityId===registration.id);assert.equal(topicNotices.filter(x=>x.type==="TOPIC_REVIEWED").length,2);assert.ok(topicNotices.every(x=>["REQUIRES_REVISION","APPROVED"].some(status=>x.message.includes(status))));
  assert.equal(Number((await pool.request().input("Id",sql.Int,registration.id).query("SELECT COUNT(*) total FROM TopicReviewHistory WHERE TopicRegistrationId=@Id")).recordset[0].total),2);

  await enroll(classA.id,[users.get("SV003").id]);await requestAs(recorder,`/groups/${group.id}/members`,{token:leader.accessToken,method:"POST",body:{studentId:users.get("SV003").id}});await requestAs(recorder,`/groups/${group.id}/members/${users.get("SV003").id}`,{token:leader.accessToken,method:"DELETE"});await requestAs(recorder,`/groups/${group.id}/members/${users.get("SV001").id}`,{token:leader.accessToken,method:"DELETE",expected:[409]});await requestAs(recorder,`/groups/${group.id}/leader`,{token:leader.accessToken,method:"PATCH",body:{studentId:users.get("SV002").id}});await requestAs(recorder,`/groups/${group.id}/leader`,{token:member.accessToken,method:"PATCH",body:{studentId:users.get("SV001").id}});await requestAs(recorder,`/groups/${group.id}`,{token:leader.accessToken,method:"DELETE",expected:[404]});
  await requestAs(recorder,"/admin/course-enrollments/transfer",{token:admin.accessToken,method:"POST",expected:[409],body:{studentId:users.get("SV001").id,sourceCourseClassId:classA.id,targetCourseClassId:classB.id,reason:"REG topic lock"}});
  const preserved=await requestAs(recorder,`/lecturer/topic-registrations/${registration.id}`,{token:lecturer.accessToken});assert.equal(preserved.data.status,"APPROVED");assert.equal((await requestAs(recorder,`/groups/${group.id}`,{token:leader.accessToken})).data.members.length,2);
  await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"CLOSED"}});await requestAs(recorder,`/lecturer/topic-rounds/${main.id}/status`,{token:lecturer.accessToken,method:"PATCH",body:{status:"CLOSED"}});await requestAs(recorder,`/student/topic-rounds/${main.id}/registration`,{token:leader.accessToken,method:"PUT",expected:[409],body:revisedTopic});assert.ok((await requestAs(recorder,`/groups/${group.id}/topic-registration`,{token:leader.accessToken})).data);
  await requestAs(recorder,`/lecturer/topic-rounds/files/${pdfMeta.id}`,{token:lecturer.accessToken,method:"DELETE",expected:[409]});
 }finally{cleanup=await cleanupRegressionData(context);printSummary("topic-workflow",recorder,cleanup);}
});
